/**
 * Genera i descarrega un fitxer CSV a partir de les dades d'un assaig.
 * @param {string} filename - El nom del fitxer a descarregar (p. ex., "assaig_torsio.csv").
 * @param {string[]} headers - Un array amb els noms de les columnes (p. ex., ["Angle (rad)", "Moment (N·m)"]).
 * @param {{x: number, y: number}[]} data - L'array de punts de dades de la simulació.
 */
function exportDataToCSV(filename, headers, data) {
  // Converteix els headers en una línia de text separada per punt i coma.
  const headerRow = headers.join(';');

  // Converteix cada punt de dada en una línia de text.
  const dataRows = data.map(point => `${point.x.toFixed(4)};${point.y.toFixed(4)}`);

  // Uneix els headers i les dades en un únic contingut CSV.
  const csvContent = [headerRow, ...dataRows].join('\n');

  // Crea un objecte Blob per manejar correctament els caràcters (com accents o 'º').
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });

  // Crea un enllaç temporal a la memòria per iniciar la descàrrega.
  const link = document.createElement("a");
  if (link.download !== undefined) { // Comprovació de compatibilitat del navegador
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

/**
 * Genera i descarrega un fitxer CSV amb múltiples columnes personalitzades.
 * @param {string} filename - El nom del fitxer a descarregar.
 * @param {string[]} headers - Un array amb els noms de les columnes.
 * @param {object[]} data - L'array d'objectes de dades.
 * @param {function} rowFormatter - Una funció que converteix un objecte de dades en una fila de CSV.
 */
function exportCustomCSV(filename, headers, data, rowFormatter) {
    const headerRow = headers.join(';');
    const dataRows = data.map(rowFormatter);

    const csvContent = [headerRow, ...dataRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.setAttribute('href', url);
    a.setAttribute('download', filename);
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
}

// --- Gestió del Tema (Mode Clar/Fosc) ---

/**
 * Aplica el tema guardat a localStorage o el preferit del sistema.
 * Aquesta funció s'ha de cridar des d'un script a l'<head> per evitar el "flash of unstyled content".
 */
function applyInitialTheme() {
    const isDarkMode = localStorage.theme === 'dark' || 
                       (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (isDarkMode) {
        document.documentElement.classList.add('dark');
    } else {
        document.documentElement.classList.remove('dark');
    }
}

/**
 * Configura el botó per canviar entre tema clar i fosc.
 * @param {HTMLElement} button - L'element del botó que controlarà el tema.
 */
function setupThemeToggler(button) {
    button.addEventListener('click', () => {
        if (document.documentElement.classList.toggle('dark')) {
            localStorage.theme = 'dark';
        } else {
            localStorage.theme = 'light';
        }
        // Disparem un esdeveniment personalitzat per si les gràfiques necessiten redibuixar-se.
        window.dispatchEvent(new CustomEvent('themeChanged'));
    });
}

// Per assegurar que s'aplica el tema el més aviat possible,
// la crida a applyInitialTheme() es farà directament a cada HTML.

// --- Gestió d'Idiomes ---

const translations = {
    'ca': { // Català / Valencià
        'main_title': "Laboratori Virtual d'Assajos de Materials",
        'main_subtitle': "Simulacions interactives per a Formació Professional",
        'select_test': "Selecciona un Assaig per Començar",
        'tensile_test': "Assaig de Tracció",
        'tensile_desc': "Simula l'estirament d'una proveta fins a la seva fractura per obtenir el diagrama Força-Allargament.",
        'compression_test': "Assaig de Compressió",
        'compression_desc': "Simula la compressió d'una proveta, típicament de formigó, fins al seu col·lapse.",
        'flexion_test': "Assaig de Flexió",
        'flexion_desc': "Simula un assaig de flexió en tres punts sobre una biga simple per determinar la seva resistència.",
        'torsion_test': "Assaig de Torsió",
        'torsion_desc': "Simula la torsió d'un eix fins a la seva fractura, obtenint el diagrama Moment-Angle.",
        'resilience_test': "Assaig de Resiliència",
        'resilience_desc': "Simula l'assaig d'impacte amb el Pèndol de Charpy per estudiar la transició dúctil-fràgil.",
        'fatigue_test': "Assaig de Fatiga",
        'fatigue_desc': "Simula l'aplicació de càrregues cícliques per determinar la vida útil d'un material (Corba S-N).",
        'return_to_menu': "Tornar al menú",
        'traction_title': "Laboratori Virtual: Tracció",
        'traction_subtitle': "Assaig de Tracció Uniaxial",
        'specimen_config': "1. Configuració de la Probeta",
        'material': "Material",
        'steel': "Acer Estructural (S275)",
        'aluminum': "Aliatge d'Alumini (6061)",
        'copper': "Coure Recuït",
        'polymer': "Polímer Rígid (PVC)",
        'length': "Longitud ($L_0$) [mm]",
        'diameter': "Diàmetre ($D_0$) [mm]",
        'area': "Àrea",
        'start_test': "Iniciar Assaig",
        'reset': "Reset",
        'test_chamber': "Cambra d'assajos",
        'current_load': "Càrrega Actual",
        'graph_title_traction': "2. Diagrama Força - Allargament",
        'real_time_sim': "Simulació en temps real",
        'data_acquisition': "3. Adquisició de Dades",
        'data_subtitle_traction': "Dades crues obtingudes del sensor de càrrega i l'extensòmetre.",
        'download_csv': "Descarregar CSV",
        'time_s': "Temps (s)",
        'force_n': "Força (N)",
        'elongation_mm': "Allargament (mm)",
        'stress_mpa': "Tensió (MPa)",
        'strain_perc': "Deformació (%)",
        'waiting_for_test': "Esperant inici de l'assaig...",
        'ready_for_new_test': "Llest per a un nou assaig",
        'elongation_mm_axis': "Allargament (mm)",
        'force_n_axis': "Força (N)",
        'compression_title': "Laboratori Virtual: Compressió",
        'compression_subtitle': "Assajos de Materials",
        'specimen_config_comp': "1. Configuració de Probeta",
        'concrete_fragile': "Materials de Construcció (Fràgils)",
        'concrete25': "Formigó HA-25 (Convencional)",
        'concrete50': "Formigó HA-50 (Alta Resistència)",
        'mortar': "Morter de Ciment (M-15)",
        'metals_ductile': "Metalls (Dúctils)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estàndard (15x30 cm per defecte)",
        'start_compression': "Iniciar Compressió",
        'new_specimen': "Nova Probeta",
        'press_chamber': "Premsa d'Assajos",
        'graph_title_comp': "2. Gràfica Tensió - Deformació",
        'graph_subtitle_comp': "Eix Y: Tensió (MPa) | Eix X: Ecurtament (%)",
        'data_acq_comp': "3. Registre de Dades",
        'data_subtitle_comp': "Valors negatius indiquen compressió (acurtament).",
        'force_kn': "Força (kN)",
        'shortening_mm': "Acurtament (mm)",
        'system_ready': "Sistema preparat. Posa proveta.",
        'flexion_title': "Laboratori Virtual: Flexió",
        'flexion_subtitle': "Assaig de Flexió en 3 Punts (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta i Material",
        'select_material': "Selecció de Material",
        'woods': "Fustes",
        'pine': "Fusta de Pi (Conífera)",
        'oak': "Fusta de Roure (Frondosa)",
        'ceramics_glass': "Ceràmics i Vidre",
        'glass': "Vidre (Fràgil)",
        'ceramic_tile': "Taulellet Ceràmic",
        'polymers': "Polímers",
        'pmma': "Metacrilat (PMMA)",
        'pp': "Polipropilè (Molt flexible)",
        'span_l': "Llum ($L$) [mm]",
        'width_b': "Ample ($b$) [mm]",
        'thickness_h': "Gruix ($h$) [mm]",
        'inertia_iz': "Moment d'Inèrcia ($I_z$):",
        'flex_test_chamber': "Cambra d'Assaig",
        'load_f': "Càrrega (F)",
        'deflection_d': "Fletxa (δ)",
        'graph_title_flex': "2. Gràfica Força vs Fletxa",
        'y_axis_force': "Eix Y: Força (N)",
        'x_axis_deflection': "Eix X: Fletxa (mm)",
        'data_acq_flex': "3. Registre de Dades",
        'flex_formulas': "Fórmules: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Força (N)",
        'deflection_mm_col': "Fletxa (mm)",
        'stress_mpa_col': "Tensió (MPa)",
        'config_specimen_start': "Configura la proveta i inicia l'assaig.",
        'break_fragile': "TRENCAMENT FRÀGIL!",
        'def_limit': "LÍMIT DEF.",
        'ready_new_test_flex': "Llest per a nou assaig.",
        'torsion_title': "Laboratori Virtual: Torsió",
        'torsion_subtitle': "Assaig de Torsió Simple (Materials Metàlics)",
        'torsion_config': "1. Configuració de l'Assaig",
        'ductile': "Dúctils",
        'fragile': "Fràgils",
        'f114_steel': "Acer F-114 (Estructural)",
        'brass': "Llautó (Aliatge Cu-Zn)",
        'cast_iron': "Fundició Gris (Ferro Colat)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Moment Polar Inèrcia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Secció massissa)",
        'start_rotation': "▶ Iniciar Gir",
        'torsion_bench': "Banc de Torsió",
        'torque': "PARELL (Torque)",
        'angle_phi': "ANGLE (φ)",
        'graph_title_torsion': "2. Diagrama Moment - Angle",
        'y_axis_torque': "Y: Parell Torsor (Nm)",
        'x_axis_angle': "X: Gir (rad)",
        'data_acq_torsion': "3. Registre de Dades",
        'shear_stress_formula': "Tensió tallant màx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angle (°)",
        'angle_rad': "Angle (rad)",
        'torque_nm': "Parell (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en repòs. Configura proveta.",
        'ready': "Llest."
    },
    'es': { // Castellà
        'main_title': "Laboratorio Virtual de Ensayos de Materiales",
        'main_subtitle': "Simulaciones interactivas para Formación Profesional",
        'select_test': "Selecciona un Ensayo para Empezar",
        'tensile_test': "Ensayo de Tracción",
        'tensile_desc': "Simula el estiramiento de una probeta hasta su fractura para obtener el diagrama Fuerza-Alargamiento.",
        'compression_test': "Ensayo de Compresión",
        'compression_desc': "Simula la compresión de una probeta, típicamente de hormigón, hasta su colapso.",
        'flexion_test': "Ensayo de Flexión",
        'flexion_desc': "Simula un ensayo de flexión en tres puntos sobre una viga simple para determinar su resistencia.",
        'torsion_test': "Ensayo de Torsión",
        'torsion_desc': "Simula la torsión de un eje hasta su fractura, obteniendo el diagrama Momento-Ángulo.",
        'resilience_test': "Ensayo de Resiliencia",
        'resilience_desc': "Simula el ensayo de impacto con el Péndulo de Charpy para estudiar la transición dúctil-frágil.",
        'fatigue_test': "Ensayo de Fatiga",
        'fatigue_desc': "Simula la aplicación de cargas cíclicas para determinar la vida útil de un material (Curva S-N).",
        'return_to_menu': "Volver al menú",
        'traction_title': "Laboratorio Virtual: Tracción",
        'traction_subtitle': "Ensayo de Tracción Uniaxial",
        'specimen_config': "1. Configuración de la Probeta",
        'material': "Material",
        'steel': "Acero Estructural (S275)",
        'aluminum': "Aleación de Aluminio (6061)",
        'copper': "Cobre Recocido",
        'polymer': "Polímero Rígido (PVC)",
        'length': "Longitud ($L_0$) [mm]",
        'diameter': "Diámetro ($D_0$) [mm]",
        'area': "Área",
        'start_test': "Iniciar Ensayo",
        'reset': "Reset",
        'test_chamber': "Cámara de ensayos",
        'current_load': "Carga Actual",
        'graph_title_traction': "2. Diagrama Fuerza - Alargamiento",
        'real_time_sim': "Simulación en tiempo real",
        'data_acquisition': "3. Adquisición de Datos",
        'data_subtitle_traction': "Datos crudos obtenidos del sensor de carga y el extensómetro.",
        'download_csv': "Descargar CSV",
        'time_s': "Tiempo (s)",
        'force_n': "Fuerza (N)",
        'elongation_mm': "Alargamiento (mm)",
        'stress_mpa': "Tensión (MPa)",
        'strain_perc': "Deformación (%)",
        'waiting_for_test': "Esperando inicio del ensayo...",
        'ready_for_new_test': "Listo para nuevo ensayo",
        'elongation_mm_axis': "Alargamiento (mm)",
        'force_n_axis': "Fuerza (N)",
        'compression_title': "Laboratorio Virtual: Compresión",
        'compression_subtitle': "Ensayos de Materiales",
        'specimen_config_comp': "1. Configuración de Probeta",
        'concrete_fragile': "Materiales de Construcción (Frágiles)",
        'concrete25': "Hormigón HA-25 (Convencional)",
        'concrete50': "Hormigón HA-50 (Alta Resistencia)",
        'mortar': "Mortero de Cemento (M-15)",
        'metals_ductile': "Metales (Dúctiles)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estándar (15x30 cm por defecto)",
        'start_compression': "Iniciar Compresión",
        'new_specimen': "Nueva Probeta",
        'press_chamber': "Prensa de Ensayos",
        'graph_title_comp': "2. Gráfica Tensión - Deformación",
        'graph_subtitle_comp': "Eje Y: Tensión (MPa) | Eje X: Acortamiento (%)",
        'data_acq_comp': "3. Registro de Datos",
        'data_subtitle_comp': "Valores negativos indican compresión (acortamiento).",
        'force_kn': "Fuerza (kN)",
        'shortening_mm': "Acortamiento (mm)",
        'system_ready': "Sistema preparado. Coloque probeta.",
        'flexion_title': "Laboratorio Virtual: Flexión",
        'flexion_subtitle': "Ensayo de Flexión en 3 Puntos (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta y Material",
        'select_material': "Selección de Material",
        'woods': "Maderas",
        'pine': "Madera de Pino (Conífera)",
        'oak': "Madera de Roble (Frondosa)",
        'ceramics_glass': "Cerámicos y Vidrio",
        'glass': "Vidrio (Frágil)",
        'ceramic_tile': "Baldosa Cerámica",
        'polymers': "Polímeros",
        'pmma': "Metacrilato (PMMA)",
        'pp': "Polipropileno (Muy flexible)",
        'span_l': "Luz ($L$) [mm]",
        'width_b': "Ancho ($b$) [mm]",
        'thickness_h': "Espesor ($h$) [mm]",
        'inertia_iz': "Momento de Inercia ($I_z$):",
        'flex_test_chamber': "Cámara de Ensayo",
        'load_f': "Carga (F)",
        'deflection_d': "Flecha (δ)",
        'graph_title_flex': "2. Gráfica Fuerza vs Flecha",
        'y_axis_force': "Eje Y: Fuerza (N)",
        'x_axis_deflection': "Eje X: Flecha (mm)",
        'data_acq_flex': "3. Registro de Datos",
        'flex_formulas': "Fórmulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Fuerza (N)",
        'deflection_mm_col': "Flecha (mm)",
        'stress_mpa_col': "Tensión (MPa)",
        'config_specimen_start': "Configura la probeta e inicia el ensayo.",
        'break_fragile': "¡ROTURA FRÁGIL!",
        'def_limit': "LÍMITE DEF.",
        'ready_new_test_flex': "Listo para nuevo ensayo.",
        'torsion_title': "Laboratorio Virtual: Torsión",
        'torsion_subtitle': "Ensayo de Torsión Simple (Materiales Metálicos)",
        'torsion_config': "1. Configuración del Ensayo",
        'ductile': "Dúctiles",
        'fragile': "Frágiles",
        'f114_steel': "Acero F-114 (Estructural)",
        'brass': "Latón (Aleación Cu-Zn)",
        'cast_iron': "Fundición Gris (Hierro Colado)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Momento Polar de Inercia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Sección maciza)",
        'start_rotation': "▶ Iniciar Giro",
        'torsion_bench': "Banco de Torsión",
        'torque': "PAR (Torque)",
        'angle_phi': "ÁNGULO (φ)",
        'graph_title_torsion': "2. Diagrama Momento - Ángulo",
        'y_axis_torque': "Y: Par Torsor (Nm)",
        'x_axis_angle': "X: Giro (rad)",
        'data_acq_torsion': "3. Registro de Datos",
        'shear_stress_formula': "Tensión cortante máx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Ángulo (°)",
        'angle_rad': "Ángulo (rad)",
        'torque_nm': "Par (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en reposo. Configura probeta.",
        'ready': "Listo."
    },
    'en': { // Anglès
        'main_title': "Virtual Materials Testing Laboratory",
        'main_subtitle': "Interactive simulations for Vocational Training",
        'select_test': "Select a Test to Begin",
        'tensile_test': "Tensile Test",
        'tensile_desc': "Simulates stretching a specimen to failure to obtain the Force-Elongation diagram.",
        'compression_test': "Compression Test",
        'compression_desc': "Simulates the compression of a specimen, typically concrete, until it collapses.",
        'flexion_test': "Flexion (Bending) Test",
        'flexion_desc': "Simulates a three-point bending test on a simple beam to determine its strength.",
        'torsion_test': "Torsion Test",
        'torsion_desc': "Simulates twisting a shaft to failure, obtaining the Torque-Angle diagram.",
        'resilience_test': "Resilience Test",
        'resilience_desc': "Simulates the Charpy pendulum impact test to study the ductile-brittle transition.",
        'fatigue_test': "Fatigue Test",
        'fatigue_desc': "Simulates cyclic loading to determine the service life of a material (S-N Curve).",
        'return_to_menu': "Return to menu",
        'traction_title': "Virtual Lab: Tensile Test",
        'traction_subtitle': "Uniaxial Tensile Test",
        'specimen_config': "1. Specimen Configuration",
        'material': "Material",
        'steel': "Structural Steel (S275)",
        'aluminum': "Aluminum Alloy (6061)",
        'copper': "Annealed Copper",
        'polymer': "Rigid Polymer (PVC)",
        'length': "Length ($L_0$) [mm]",
        'diameter': "Diameter ($D_0$) [mm]",
        'area': "Area",
        'start_test': "Start Test",
        'reset': "Reset",
        'test_chamber': "Test Chamber",
        'current_load': "Current Load",
        'graph_title_traction': "2. Force - Elongation Diagram",
        'real_time_sim': "Real-time simulation",
        'data_acquisition': "3. Data Acquisition",
        'data_subtitle_traction': "Raw data from the load cell and extensometer.",
        'download_csv': "Download CSV",
        'time_s': "Time (s)",
        'force_n': "Force (N)",
        'elongation_mm': "Elongation (mm)",
        'stress_mpa': "Stress (MPa)",
        'strain_perc': "Strain (%)",
        'waiting_for_test': "Waiting for test to start...",
        'ready_for_new_test': "Ready for new test",
        'elongation_mm_axis': "Elongation (mm)",
        'force_n_axis': "Force (N)",
        'compression_title': "Virtual Lab: Compression",
        'compression_subtitle': "Materials Testing",
        'specimen_config_comp': "1. Specimen Configuration",
        'concrete_fragile': "Construction Materials (Brittle)",
        'concrete25': "Concrete HA-25 (Conventional)",
        'concrete50': "Concrete HA-50 (High-Strength)",
        'mortar': "Cement Mortar (M-15)",
        'metals_ductile': "Metals (Ductile)",
        'height': "Height ($H_0$) [mm]",
        'std_specimen_comp': "* Standard Cylindrical Specimen (15x30 cm by default)",
        'start_compression': "Start Compression",
        'new_specimen': "New Specimen",
        'press_chamber': "Testing Press",
        'graph_title_comp': "2. Stress - Strain Graph",
        'graph_subtitle_comp': "Y-axis: Stress (MPa) | X-axis: Shortening (%)",
        'data_acq_comp': "3. Data Log",
        'data_subtitle_comp': "Negative values indicate compression (shortening).",
        'force_kn': "Force (kN)",
        'shortening_mm': "Shortening (mm)",
        'system_ready': "System ready. Place specimen.",
        'flexion_title': "Virtual Lab: Bending",
        'flexion_subtitle': "3-Point Bending Test (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Specimen and Material",
        'select_material': "Material Selection",
        'woods': "Woods",
        'pine': "Pine Wood (Softwood)",
        'oak': "Oak Wood (Hardwood)",
        'ceramics_glass': "Ceramics & Glass",
        'glass': "Glass (Brittle)",
        'ceramic_tile': "Ceramic Tile",
        'polymers': "Polymers",
        'pmma': "Acrylic (PMMA)",
        'pp': "Polypropylene (Very flexible)",
        'span_l': "Span ($L$) [mm]",
        'width_b': "Width ($b$) [mm]",
        'thickness_h': "Thickness ($h$) [mm]",
        'inertia_iz': "Moment of Inertia ($I_z$):",
        'flex_test_chamber': "Test Chamber",
        'load_f': "Load (F)",
        'deflection_d': "Deflection (δ)",
        'graph_title_flex': "2. Force vs Deflection Graph",
        'y_axis_force': "Y-axis: Force (N)",
        'x_axis_deflection': "X-axis: Deflection (mm)",
        'data_acq_flex': "3. Data Log",
        'flex_formulas': "Formulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Force (N)",
        'deflection_mm_col': "Deflection (mm)",
        'stress_mpa_col': "Stress (MPa)",
        'config_specimen_start': "Configure the specimen and start the test.",
        'break_fragile': "BRITTLE FAILURE!",
        'def_limit': "DEF. LIMIT",
        'ready_new_test_flex': "Ready for new test.",
        'torsion_title': "Virtual Lab: Torsion",
        'torsion_subtitle': "Simple Torsion Test (Metallic Materials)",
        'torsion_config': "1. Test Configuration",
        'ductile': "Ductile",
        'fragile': "Brittle",
        'f114_steel': "F-114 Steel (Structural)",
        'brass': "Brass (Cu-Zn Alloy)",
        'cast_iron': "Gray Cast Iron",
        'nylon': "Nylon (Polyamide)",
        'polar_moment': "Polar Moment of Inertia ($J$):",
        'polar_moment_formula': "Formula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Solid section)",
        'start_rotation': "▶ Start Rotation",
        'torsion_bench': "Torsion Bench",
        'torque': "TORQUE",
        'angle_phi': "ANGLE (φ)",
        'graph_title_torsion': "2. Torque - Angle Diagram",
        'y_axis_torque': "Y: Torque (Nm)",
        'x_axis_angle': "X: Angle (rad)",
        'data_acq_torsion': "3. Data Log",
        'shear_stress_formula': "Max shear stress: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angle (°)",
        'angle_rad': "Angle (rad)",
        'torque_nm': "Torque (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "System idle. Configure specimen.",
        'ready': "Ready."
    },
    'eu': { // Basc
        'main_title': "Materialen Saiakuntzen Laborategi Birtuala",
        'main_subtitle': "Lanbide Heziketarako simulazio interaktiboak",
        'select_test': "Hautatu Saiakuntza bat Hasteko",
        'tensile_test': "Trakzio Saiakuntza",
        'tensile_desc': "Probeta baten luzapena simulatzen du, hausturara iritsi arte, Indar-Luzapen diagrama lortzeko.",
        'compression_test': "Konpresio Saiakuntza",
        'compression_desc': "Probeta baten konpresioa simulatzen du, normalean hormigoia, kolapsatu arte.",
        'flexion_test': "Makurdura Saiakuntza",
        'flexion_desc': "Hiru puntuko makurdura-saiakuntza simulatzen du habe sinple batean, haren erresistentzia zehazteko.",
        'torsion_test': "Tortsio Saiakuntza",
        'torsion_desc': "Ardatz baten tortsioa simulatzen du, hausturara iritsi arte, Momentu-Angelu diagrama lortuz.",
        'resilience_test': "Erresilientzia Saiakuntza",
        'resilience_desc': "Charpy penduluaren talka-saiakuntza simulatzen du, trantsizio harikor-hauskorra aztertzeko.",
        'fatigue_test': "Neke Saiakuntza",
        'fatigue_desc': "Karga ziklikoen aplikazioa simulatzen du material baten bizitza erabilgarria zehazteko (S-N Kurba).",
        'return_to_menu': "Itzuli menura",
        'traction_title': "Laborategi Birtuala: Trakzioa",
        'traction_subtitle': "Trakzio Uniaxialeko Saiakuntza",
        'specimen_config': "1. Probetaren Konfigurazioa",
        'material': "Materiala",
        'steel': "Egiturazko Altzairua (S275)",
        'aluminum': "Aluminio Aleazioa (6061)",
        'copper': "Kobre Egosia",
        'polymer': "Polimero Zurruna (PVC)",
        'length': "Luzera ($L_0$) [mm]",
        'diameter': "Diametroa ($D_0$) [mm]",
        'area': "Azalera",
        'start_test': "Hasi Saiakuntza",
        'reset': "Berrezarri",
        'test_chamber': "Saiakuntza-ganbera",
        'current_load': "Uneko Karga",
        'graph_title_traction': "2. Indar - Luzapen Diagrama",
        'real_time_sim': "Denbora errealeko simulazioa",
        'data_acquisition': "3. Datu-bilketa",
        'data_subtitle_traction': "Karga-sentsoretik eta estentsometrotik lortutako datu gordinak.",
        'download_csv': "Deskargatu CSV",
        'time_s': "Denbora (s)",
        'force_n': "Indarra (N)",
        'elongation_mm': "Luzapena (mm)",
        'stress_mpa': "Tentsioa (MPa)",
        'strain_perc': "Deformazioa (%)",
        'waiting_for_test': "Saiakuntza noiz hasiko zain...",
        'ready_for_new_test': "Saiakuntza berrirako prest",
        'elongation_mm_axis': "Luzapena (mm)",
        'force_n_axis': "Indarra (N)",
        'compression_title': "Laborategi Birtuala: Konpresioa",
        'compression_subtitle': "Materialen Saiakuntzak",
        'specimen_config_comp': "1. Probetaren Konfigurazioa",
        'concrete_fragile': "Eraikuntzako Materialak (Hauskorrak)",
        'concrete25': "Hormigoi HA-25 (Ohikoa)",
        'concrete50': "Hormigoi HA-50 (Erresistentzia Handikoa)",
        'mortar': "Zementuzko Morteroa (M-15)",
        'metals_ductile': "Metalak (Harikorrak)",
        'height': "Altuera ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Zilindriko Estandarra (15x30 cm lehenetsita)",
        'start_compression': "Hasi Konpresioa",
        'new_specimen': "Probeta Berria",
        'press_chamber': "Saiakuntza Prentsa",
        'graph_title_comp': "2. Tentsio - Deformazio Grafikoa",
        'graph_subtitle_comp': "Y ardatza: Tentsioa (MPa) | X ardatza: Laburtzea (%)",
        'data_acq_comp': "3. Datuen Erregistroa",
        'data_subtitle_comp': "Balio negatiboek konpresioa (laburtzea) adierazten dute.",
        'force_kn': "Indarra (kN)",
        'shortening_mm': "Laburtzea (mm)",
        'system_ready': "Sistema prest. Jarri probeta.",
        'flexion_title': "Laborategi Birtuala: Makurdura",
        'flexion_subtitle': "3 Puntuko Makurdura Saiakuntza (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta eta Materiala",
        'select_material': "Materiala Aukeratu",
        'woods': "Egurrak",
        'pine': "Pinu-zura (Koniferoa)",
        'oak': "Haritz-zura (Hostozabala)",
        'ceramics_glass': "Zeramikak eta Beira",
        'glass': "Beira (Hauskorra)",
        'ceramic_tile': "Zeramikazko Laukia",
        'polymers': "Polimeroak",
        'pmma': "Metakrilatoa (PMMA)",
        'pp': "Polipropilenoa (Oso malgua)",
        'span_l': "Argi-zuloa ($L$) [mm]",
        'width_b': "Zabalera ($b$) [mm]",
        'thickness_h': "Lodiera ($h$) [mm]",
        'inertia_iz': "Inertzia Momentua ($I_z$):",
        'flex_test_chamber': "Saiakuntza Ganbera",
        'load_f': "Karga (F)",
        'deflection_d': "Gezi (δ)",
        'graph_title_flex': "2. Indarra vs Gezi Grafikoa",
        'y_axis_force': "Y ardatza: Indarra (N)",
        'x_axis_deflection': "X ardatza: Gezia (mm)",
        'data_acq_flex': "3. Datuen Erregistroa",
        'flex_formulas': "Formulak: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Indarra (N)",
        'deflection_mm_col': "Gezia (mm)",
        'stress_mpa_col': "Tentsioa (MPa)",
        'config_specimen_start': "Konfiguratu probeta eta hasi saiakuntza.",
        'break_fragile': "HAUSTURA HAUSKORRA!",
        'def_limit': "DEF. MUGA",
        'ready_new_test_flex': "Saiakuntza berrirako prest.",
        'torsion_title': "Laborategi Birtuala: Tortsioa",
        'torsion_subtitle': "Tortsio Saiakuntza Sinplea (Material Metalikoak)",
        'torsion_config': "1. Saiakuntzaren Konfigurazioa",
        'ductile': "Harikorrak",
        'fragile': "Hauskorrak",
        'f114_steel': "F-114 Altzairua (Egiturazkoa)",
        'brass': "Letoia (Cu-Zn Aleazioa)",
        'cast_iron': "Burdinurtu Grisa",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Inertzia Momentu Polarra ($J$):",
        'polar_moment_formula': "Formula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Atal trinkoa)",
        'start_rotation': "▶ Hasi Biraketa",
        'torsion_bench': "Tortsio Bankua",
        'torque': "BIHURDURA",
        'angle_phi': "ANGELUA (φ)",
        'graph_title_torsion': "2. Momentu - Angelu Diagrama",
        'y_axis_torque': "Y: Momentu Bihurtzailea (Nm)",
        'x_axis_angle': "X: Biraketa (rad)",
        'data_acq_torsion': "3. Datuen Erregistroa",
        'shear_stress_formula': "Ebakidura-tentsio max: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angelua (°)",
        'angle_rad': "Angelua (rad)",
        'torque_nm': "Momentua (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema geldirik. Konfiguratu probeta.",
        'ready': "Prest."
    },
    'gl': { // Gallec
        'main_title': "Laboratorio Virtual de Ensaios de Materiais",
        'main_subtitle': "Simulacións interactivas para Formación Profesional",
        'select_test': "Selecciona un Ensaio para Comezar",
        'tensile_test': "Ensaio de Tracción",
        'tensile_desc': "Simula o estiramento dunha probeta ata a súa fractura para obter o diagrama Forza-Alongamento.",
        'compression_test': "Ensaio de Compresión",
        'compression_desc': "Simula a compresión dunha probeta, normalmente de formigón, ata o seu colapso.",
        'flexion_test': "Ensaio de Flexión",
        'flexion_desc': "Simula un ensaio de flexión en tres puntos sobre unha viga simple para determinar a súa resistencia.",
        'torsion_test': "Ensaio de Torsión",
        'torsion_desc': "Simula a torsión dun eixe ata a súa fractura, obtendo o diagrama Momento-Ángulo.",
        'resilience_test': "Ensaio de Resiliencia",
        'resilience_desc': "Simula o ensaio de impacto co Péndulo de Charpy para estudar a transición dúctil-fráxil.",
        'fatigue_test': "Ensaio de Fatiga",
        'fatigue_desc': "Simula a aplicación de cargas cíclicas para determinar a vida útil dun material (Curva S-N).",
        'return_to_menu': "Volver ao menú",
        'traction_title': "Laboratorio Virtual: Tracción",
        'traction_subtitle': "Ensaio de Tracción Uniaxial",
        'specimen_config': "1. Configuración da Probeta",
        'material': "Material",
        'steel': "Aceiro Estrutural (S275)",
        'aluminum': "Aliaxe de Aluminio (6061)",
        'copper': "Cobre Recocido",
        'polymer': "Polímero Ríxido (PVC)",
        'length': "Lonxitude ($L_0$) [mm]",
        'diameter': "Diámetro ($D_0$) [mm]",
        'area': "Área",
        'start_test': "Iniciar Ensaio",
        'reset': "Reset",
        'test_chamber': "Cámara de ensaios",
        'current_load': "Carga Actual",
        'graph_title_traction': "2. Diagrama Forza - Alongamento",
        'real_time_sim': "Simulación en tempo real",
        'data_acquisition': "3. Adquisición de Datos",
        'data_subtitle_traction': "Datos crus obtidos do sensor de carga e o extensómetro.",
        'download_csv': "Descargar CSV",
        'time_s': "Tempo (s)",
        'force_n': "Forza (N)",
        'elongation_mm': "Alongamento (mm)",
        'stress_mpa': "Tensión (MPa)",
        'strain_perc': "Deformación (%)",
        'waiting_for_test': "Agardando inicio do ensaio...",
        'ready_for_new_test': "Listo para novo ensaio",
        'elongation_mm_axis': "Alongamento (mm)",
        'force_n_axis': "Forza (N)",
        'compression_title': "Laboratorio Virtual: Compresión",
        'compression_subtitle': "Ensaios de Materiais",
        'specimen_config_comp': "1. Configuración da Probeta",
        'concrete_fragile': "Materiais de Construción (Fráxiles)",
        'concrete25': "Formigón HA-25 (Convencional)",
        'concrete50': "Formigón HA-50 (Alta Resistencia)",
        'mortar': "Morteiro de Cemento (M-15)",
        'metals_ductile': "Metais (Dúctiles)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estándar (15x30 cm por defecto)",
        'start_compression': "Iniciar Compresión",
        'new_specimen': "Nova Probeta",
        'press_chamber': "Prensa de Ensaios",
        'graph_title_comp': "2. Gráfica Tensión - Deformación",
        'graph_subtitle_comp': "Eixo Y: Tensión (MPa) | Eixo X: Acurtamento (%)",
        'data_acq_comp': "3. Rexistro de Datos",
        'data_subtitle_comp': "Valores negativos indican compresión (acurtamento).",
        'force_kn': "Forza (kN)",
        'shortening_mm': "Acurtamento (mm)",
        'system_ready': "Sistema preparado. Coloque a probeta.",
        'flexion_title': "Laboratorio Virtual: Flexión",
        'flexion_subtitle': "Ensaio de Flexión en 3 Puntos (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta e Material",
        'select_material': "Selección de Material",
        'woods': "Madeiras",
        'pine': "Madeira de Piñeiro (Conífera)",
        'oak': "Madeira de Carballo (Frondosa)",
        'ceramics_glass': "Cerámicos e Vidro",
        'glass': "Vidro (Fráxil)",
        'ceramic_tile': "Baldosa Cerámica",
        'polymers': "Polímeros",
        'pmma': "Metacrilato (PMMA)",
        'pp': "Polipropileno (Moi flexible)",
        'span_l': "Luz ($L$) [mm]",
        'width_b': "Ancho ($b$) [mm]",
        'thickness_h': "Espesor ($h$) [mm]",
        'inertia_iz': "Momento de Inercia ($I_z$):",
        'flex_test_chamber': "Cámara de Ensaio",
        'load_f': "Carga (F)",
        'deflection_d': "Frecha (δ)",
        'graph_title_flex': "2. Gráfica Forza vs Frecha",
        'y_axis_force': "Eixo Y: Forza (N)",
        'x_axis_deflection': "Eixo X: Frecha (mm)",
        'data_acq_flex': "3. Rexistro de Datos",
        'flex_formulas': "Fórmulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Forza (N)",
        'deflection_mm_col': "Frecha (mm)",
        'stress_mpa_col': "Tensión (MPa)",
        'config_specimen_start': "Configura a probeta e inicia o ensaio.",
        'break_fragile': "ROTURA FRÁXIL!",
        'def_limit': "LÍMITE DEF.",
        'ready_new_test_flex': "Listo para novo ensaio.",
        'torsion_title': "Laboratorio Virtual: Torsión",
        'torsion_subtitle': "Ensaio de Torsión Simple (Materiais Metálicos)",
        'torsion_config': "1. Configuración do Ensaio",
        'ductile': "Dúctiles",
        'fragile': "Fráxiles",
        'f114_steel': "Aceiro F-114 (Estrutural)",
        'brass': "Latón (Aliaxe Cu-Zn)",
        'cast_iron': "Fundición Gris (Ferro Fundido)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Momento Polar de Inercia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Sección maciza)",
        'start_rotation': "▶ Iniciar Xiro",
        'torsion_bench': "Banco de Torsión",
        'torque': "PAR (Torque)",
        'angle_phi': "ÁNGULO (φ)",
        'graph_title_torsion': "2. Diagrama Momento - Ángulo",
        'y_axis_torque': "Y: Par Torsor (Nm)",
        'x_axis_angle': "X: Xiro (rad)",
        'data_acq_torsion': "3. Rexistro de Datos",
        'shear_stress_formula': "Tensión cortante máx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Ángulo (°)",
        'angle_rad': "Ángulo (rad)",
        'torque_nm': "Par (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en repouso. Configura probeta.",
        'ready': "Listo."
    }
};

/**
 * Estableix l'idioma seleccionat, el desa i aplica les traduccions.
 * @param {string} lang - El codi de l'idioma (p. ex., 'ca', 'es').
 */
function setLanguage(lang) {
    localStorage.setItem('language', lang);
    applyTranslations();
    // Oculta el menú desplegable després de la selecció
    const langMenu = document.getElementById('lang-menu');
    if (langMenu) {
        langMenu.classList.add('hidden');
    }
}

/**
 * Aplica les traduccions a tots els elements marcats amb 'data-translate'.
 */
function applyTranslations() {
    const lang = localStorage.getItem('language') || 'ca';
    const dictionary = translations[lang] || translations['ca'];

    document.querySelectorAll('[data-translate]').forEach(el => {
        const key = el.getAttribute('data-translate');
        if (dictionary[key]) {
            el.innerHTML = dictionary[key];
        }
    });
}
