/**
 * Genera i descarrega un fitxer CSV a partir de les dades d'un assaig.
 * @param {string} filename - El nom del fitxer a descarregar (p. ex., "assaig_torsio.csv").
 * @param {string[]} headers - Un array amb els noms de les columnes (p. ex., ["Angle (rad)", "Moment (N·m)"]).
 * @param {{x: number, y: number}[]} data - L'array de punts de dades de la simulació.
 */
function exportDataToCSV(filename, headers, data) {
  // Converteix els headers en una línia de text separada per punt i coma.
  const headerRow = headers.join(';');

  // Converteix cada punt de dada en una línia de text.
  const dataRows = data.map(point => `${point.x.toFixed(4)};${point.y.toFixed(4)}`);

  // Uneix els headers i les dades en un únic contingut CSV.
  const csvContent = [headerRow, ...dataRows].join('\n');

  // Crea un objecte Blob per manejar correctament els caràcters (com accents o 'º').
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });

  // Crea un enllaç temporal a la memòria per iniciar la descàrrega.
  const link = document.createElement("a");
  if (link.download !== undefined) { // Comprovació de compatibilitat del navegador
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

/**
 * Genera i descarrega un fitxer CSV amb múltiples columnes personalitzades.
 * @param {string} filename - El nom del fitxer a descarregar.
 * @param {string[]} headers - Un array amb els noms de les columnes.
 * @param {object[]} data - L'array d'objectes de dades.
 * @param {function} rowFormatter - Una funció que converteix un objecte de dades en una fila de CSV.
 */
function exportCustomCSV(filename, headers, data, rowFormatter) {
    const headerRow = headers.join(';');
    const dataRows = data.map(rowFormatter);

    const csvContent = [headerRow, ...dataRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.setAttribute('href', url);
    a.setAttribute('download', filename);
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
}

// --- Gestió del Tema (Mode Clar/Fosc) ---

/**
 * Aplica el tema guardat a localStorage o el preferit del sistema.
 * Aquesta funció s'ha de cridar des d'un script a l'<head> per evitar el "flash of unstyled content".
 */
function applyInitialTheme() {
    const isDarkMode = localStorage.theme === 'dark' || 
                       (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (isDarkMode) {
        document.documentElement.classList.add('dark');
    } else {
        document.documentElement.classList.remove('dark');
    }
}

/**
 * Configura el botó per canviar entre tema clar i fosc.
 * @param {HTMLElement} button - L'element del botó que controlarà el tema.
 */
function setupThemeToggler(button) {
    button.addEventListener('click', () => {
        if (document.documentElement.classList.toggle('dark')) {
            localStorage.theme = 'dark';
        } else {
            localStorage.theme = 'light';
        }
        // Disparem un esdeveniment personalitzat per si les gràfiques necessiten redibuixar-se.
        window.dispatchEvent(new CustomEvent('themeChanged'));
    });
}

// Per assegurar que s'aplica el tema el més aviat possible,
// la crida a applyInitialTheme() es farà directament a cada HTML.

// --- Gestió d'Idiomes ---

const translations = {
    'ca': { // Català / Valencià
        'main_title': "Laboratori Virtual d'Assajos de Materials",
        'main_subtitle': "Simulacions interactives per a Formació Professional",
        'select_test': "Selecciona un Assaig per Començar",
        'tensile_test': "Assaig de Tracció",
        'tensile_desc': "Simula l'estirament d'una proveta fins a la seva fractura per obtenir el diagrama Força-Allargament.",
        'compression_test': "Assaig de Compressió",
        'compression_desc': "Simula la compressió d'una proveta, típicament de formigó, fins al seu col·lapse.",
        'flexion_test': "Assaig de Flexió",
        'flexion_desc': "Simula un assaig de flexió en tres punts sobre una biga simple per determinar la seva resistència.",
        'torsion_test': "Assaig de Torsió",
        'torsion_desc': "Simula la torsió d'un eix fins a la seva fractura, obtenint el diagrama Moment-Angle.",
        'resilience_test': "Assaig de Resiliència",
        'resilience_desc': "Simula l'assaig d'impacte amb el Pèndol de Charpy per estudiar la transició dúctil-fràgil.",
        'fatigue_test': "Assaig de Fatiga",
        'fatigue_desc': "Simula l'aplicació de càrregues cícliques per determinar la vida útil d'un material (Corba S-N).",
        'return_to_menu': "Tornar al menú",
        'traction_title': "Laboratori Virtual: Tracció",
        'traction_subtitle': "Assaig de Tracció Uniaxial",
        'specimen_config': "1. Configuració de la Probeta",
        'material': "Material",
        'machine_limit': "Límit de Força de la Màquina",
        'steel': "Acer Estructural (S275)",
        'aluminum': "Aliatge d'Alumini (6061)",
        'copper': "Coure Recuït",
        'polymer': "Polímer Rígid (PVC)",
        'length': "Longitud ($L_0$) [mm]",
        'diameter': "Diàmetre ($D_0$) [mm]",
        'area': "Àrea",
        'start_test': "Iniciar Assaig",
        'reset': "Reset",
        'test_chamber': "Cambra d'assajos",
        'current_load': "Càrrega Actual",
        'graph_title_traction': "2. Diagrama Força - Allargament",
        'real_time_sim': "Simulació en temps real",
        'data_acquisition': "3. Adquisició de Dades",
        'data_subtitle_traction': "Dades crues obtingudes del sensor de càrrega i l'extensòmetre.",
        'download_csv': "Descarregar CSV",
        'time_s': "Temps (s)",
        'force_n': "Força (N)",
        'elongation_mm': "Allargament (mm)",
        'stress_mpa': "Tensió (MPa)",
        'strain_perc': "Deformació (%)",
        'waiting_for_test': "Esperant inici de l'assaig...",
        'ready_for_new_test': "Llest per a un nou assaig",
        'elongation_mm_axis': "Allargament (mm)",
        'force_n_axis': "Força (N)",
        'compression_title': "Laboratori Virtual: Compressió",
        'compression_subtitle': "Assajos de Materials",
        'specimen_config_comp': "1. Configuració de Probeta",
        'concrete_fragile': "Materials de Construcció (Fràgils)",
        'pine_wood': "Fusta de Pi",
        'concrete25': "Formigó HA-25 (Convencional)",
        'concrete50': "Formigó HA-50 (Alta Resistència)",
        'mortar': "Morter de Ciment (M-15)",
        'metals_ductile': "Metalls (Dúctils)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estàndard (15x30 cm per defecte)",
        'start_compression': "Iniciar Compressió",
        'new_specimen': "Nova Probeta",
        'press_chamber': "Premsa d'Assajos",
        'graph_title_comp': "2. Gràfica Tensió - Deformació",
        'graph_subtitle_comp': "Eix Y: Tensió (MPa) | Eix X: Ecurtament (%)",
        'data_acq_comp': "3. Registre de Dades",
        'data_subtitle_comp': "Valors negatius indiquen compressió (acurtament).",
        'force_kn': "Força (kN)",
        'shortening_mm': "Acurtament (mm)",
        'system_ready': "Sistema preparat. Posa proveta.",
        'pvc': "PVC Rígid",
        'flexion_title': "Laboratori Virtual: Flexió",
        'flexion_subtitle': "Assaig de Flexió en 3 Punts (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta i Material",
        'select_material': "Selecció de Material",
        'woods': "Fustes",
        'pine': "Fusta de Pi (Conífera)",
        'oak': "Fusta de Roure (Frondosa)",
        'ceramics_glass': "Ceràmics i Vidre",
        'glass': "Vidre (Fràgil)",
        'ceramic_tile': "Taulellet Ceràmic",
        'polymers': "Polímers",
        'pmma': "Metacrilat (PMMA)",
        'pp': "Polipropilè (Molt flexible)",
        'span_l': "Llum ($L$) [mm]",
        'width_b': "Ample ($b$) [mm]",
        'thickness_h': "Gruix ($h$) [mm]",
        'inertia_iz': "Moment d'Inèrcia ($I_z$):",
        'flex_test_chamber': "Cambra d'Assaig",
        'load_f': "Càrrega (F)",
        'deflection_d': "Fletxa (δ)",
        'graph_title_flex': "2. Gràfica Força vs Fletxa",
        'y_axis_force': "Eix Y: Força (N)",
        'x_axis_deflection': "Eix X: Fletxa (mm)",
        'data_acq_flex': "3. Registre de Dades",
        'flex_formulas': "Fórmules: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Força (N)",
        'deflection_mm_col': "Fletxa (mm)",
        'stress_mpa_col': "Tensió (MPa)",
        'config_specimen_start': "Configura la proveta i inicia l'assaig.",
        'break_fragile': "TRENCAMENT FRÀGIL!",
        'def_limit': "LÍMIT DEF.",
        'educational_bench': "1 kN (Banc Educatiu)",
        'standard_lab_flexion': "10 kN (Estàndard Laboratori)",
        'high_capacity_flexion': "100 kN (Alta Capacitat)",
        'ready_new_test_flex': "Llest per a nou assaig.",
        'torsion_title': "Laboratori Virtual: Torsió",
        'torsion_subtitle': "Assaig de Torsió Simple (Materials Metàlics)",
        'torsion_config': "1. Configuració de l'Assaig",
        'ductile': "Dúctils",
        'fragile': "Fràgils",
        'f114_steel': "Acer F-114 (Estructural)",
        'brass': "Llautó (Aliatge Cu-Zn)",
        'cast_iron': "Fundició Gris (Ferro Colat)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Moment Polar Inèrcia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Secció massissa)",
        'start_rotation': "▶ Iniciar Gir",
        'torsion_bench': "Banc de Torsió",
        'torque': "PARELL (Torque)",
        'angle_phi': "ANGLE (φ)",
        'graph_title_torsion': "2. Diagrama Moment - Angle",
        'y_axis_torque': "Y: Parell Torsor (Nm)",
        'x_axis_angle': "X: Gir (rad)",
        'data_acq_torsion': "3. Registre de Dades",
        'shear_stress_formula': "Tensió tallant màx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angle (°)",
        'angle_rad': "Angle (rad)",
        'machine_torque_limit': "Límit de Parell de la Màquina",
        'small_bench': "100 Nm (Banc Petit)",
        'standard_lab_torsion': "1000 Nm (Estàndard Laboratori)",
        'high_capacity_torsion': "5000 Nm (Alta Capacitat)",
        'torque_nm': "Parell (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en repòs. Configura proveta.",
        'ready': "Llest.",
        'fatigue_title': "Laboratori Virtual: Fatiga",
        'fatigue_subtitle': "Assaig de Càrrega Cíclica (Corba S-N)",
        'cyclic_load_params': "1. Paràmetres de Càrrega Cíclica",
        'carbon_steel': "Acer al Carboni",
        'aluminum_alloy': "Aliatge d'Alumini",
        'titanium_alloy': "Aliatge de Titani",
        'max_stress': "Tensió Màxima ($\\sigma_{max}$)",
        'stress_ratio': "Ratio de Tensions (R = $\\sigma_{min} / \\sigma_{max}$)",
        'tension_compression': "Tracció-Compressió (R=-1)",
        'tension_tension': "Tracció-Tracció (R>0)",
        'mean_stress': "Tensió Mitjana ($\\sigma_m$):",
        'stress_amplitude': "Amplitud de Tensió ($\\sigma_a$):",
        'cycle_count': "Nombre de Cicles (N)",
        'current_stress': "Tensió Actual",
        'fatigue_failure': "FALLADA PER FATIGA",
        'sn_diagram_title': "2. Diagrama S-N (Wöhler)",
        'sn_diagram_desc': "Representa l'Amplitud de Tensió ($\\sigma_a$) enfront del Nombre de Cicles fins a la fallada (N). L'eix X és logarítmic.",
        'objective': "Objectiu:",
        'objective_desc_fatigue': "Realitza assajos a diferents nivells de $\\sigma_a$ per construir la corba. Observaràs que a menor tensió, el material aguanta molts més cicles abans de trencar-se.",
        'test_results': "3. Resultats dels Assajos",
        'clear_graph': "Netejar Gràfica",
        'stress_amplitude_col': "$\\sigma_a$ (MPa)",
        'ratio_r_col': "R",
        'cycles_n_col': "Cicles (N)",
        'populate_graph': "Realitza assajos per poblar la gràfica.",
        'data_cleared': "Dades esborrades.",
        'stress_amplitude_axis': "Amplitud de Tensió, σa (MPa)",
        'cycles_to_failure_axis': "Cicles fins a Fallada, N (log scale)",
        'resilience_title': "Laboratori Virtual: Resiliència",
        'resilience_subtitle': "Assaig d'Impacte Charpy (ISO 148-1)",
        'sample_prep': "1. Preparació de la Mostra",
        'low_carbon_steel': "Acer Baix Carboni (S235)",
        'tempered_steel_desc': "Més fràgil, menor energia màxima.",
        'fcc_desc': "Xarxa FCC: No presenta transició dràstica.",
        'hcp_desc': "Alta tenacitat, corba suau.",
        'pendulum_params': "Paràmetres del Pèndol",
        'pendulum_mass': "Massa del Pèndol",
        'arm_length': "Longitud del Braç",
        'initial_energy': "Energia Potencial Inicial:",
        'high_carbon_steel': "Acer Alt Carboni (Trempat)",
        'aluminum_alloy_7075': "Aliatge Alumini (7075)",
        'titanium_alloy_ti64': "Titani (Ti-6Al-4V)",
        'bcc_desc_initial': "Presenta transició dúctil-fràgil clara.",
        'test_temp': "Temperatura d'Assaig",
        'temp_n2': "-100°C (N₂)",
        'temp_100': "+100°C",
        'release_pendulum': "Soltar Pèndol",
        'new_specimen_charpy': "Nova Probeta",
        'impact_chamber': "Cambra d'Impacte",
        'energy_kv': "ENERGIA (KV)",
        'transition_curve_title': "2. Curva de Transició Dúctil-Fràgil",
        'transition_curve_desc': "Realitzeu assajos a diferents temperatures per construir la curva.",
        'impact_log': "3. Registre d'Impactes",
        'resilience_formula': "Resiliència $\\rho = KCV / S_0$ (J/cm²)",
        'clear_data': "Esborrar Dades",
        'material_col': "Material",
        'temp_col': "Temp (°C)",
        'energy_col': "Energia (J)",
        'fracture_type_col': "Trencament",
        'add_points_temp': "Afegiu punts assajant a diferents temperatures.",
        'help_elastic_zone': "Zona Elàstica: El material es deforma però torna a la seva forma original si es retira la càrrega. La pendent d'aquesta recta és el Mòdul de Young (E).", // Aquesta clau ja existia
        'initial_height': "Alçada Inicial:",
        'final_height': "Alçada Final:",
        'help_yield_point': "Límit Elàstic (Fluència): Punt on el material comença a deformar-se plàsticament (de manera permanent).",
        'help_plastic_zone': "Zona Plàstica: El material sofreix una deformació permanent. Encara que es retiri la càrrega, no recuperarà la seva forma inicial."
    },
    'es': { // Castellà
        'main_title': "Laboratorio Virtual de Ensayos de Materiales",
        'main_subtitle': "Simulaciones interactivas para Formación Profesional",
        'select_test': "Selecciona un Ensayo para Empezar",
        'tensile_test': "Ensayo de Tracción",
        'tensile_desc': "Simula el estiramiento de una probeta hasta su fractura para obtener el diagrama Fuerza-Alargamiento.",
        'compression_test': "Ensayo de Compresión",
        'compression_desc': "Simula la compresión de una probeta, típicamente de hormigón, hasta su colapso.",
        'flexion_test': "Ensayo de Flexión",
        'flexion_desc': "Simula un ensayo de flexión en tres puntos sobre una viga simple para determinar su resistencia.",
        'torsion_test': "Ensayo de Torsión",
        'torsion_desc': "Simula la torsión de un eje hasta su fractura, obteniendo el diagrama Momento-Ángulo.",
        'resilience_test': "Ensayo de Resiliencia",
        'resilience_desc': "Simula el ensayo de impacto con el Péndulo de Charpy para estudiar la transición dúctil-frágil.",
        'fatigue_test': "Ensayo de Fatiga",
        'fatigue_desc': "Simula la aplicación de cargas cíclicas para determinar la vida útil de un material (Curva S-N).",
        'return_to_menu': "Volver al menú",
        'traction_title': "Laboratorio Virtual: Tracción",
        'traction_subtitle': "Ensayo de Tracción Uniaxial",
        'specimen_config': "1. Configuración de la Probeta",
        'material': "Material",
        'machine_limit': "Límite de Fuerza de la Máquina",
        'steel': "Acero Estructural (S275)",
        'aluminum': "Aleación de Aluminio (6061)",
        'copper': "Cobre Recocido",
        'polymer': "Polímero Rígido (PVC)",
        'length': "Longitud ($L_0$) [mm]",
        'diameter': "Diámetro ($D_0$) [mm]",
        'area': "Área",
        'start_test': "Iniciar Ensayo",
        'reset': "Reset",
        'test_chamber': "Cámara de ensayos",
        'current_load': "Carga Actual",
        'graph_title_traction': "2. Diagrama Fuerza - Alargamiento",
        'real_time_sim': "Simulación en tiempo real",
        'data_acquisition': "3. Adquisición de Datos",
        'data_subtitle_traction': "Datos crudos obtenidos del sensor de carga y el extensómetro.",
        'download_csv': "Descargar CSV",
        'time_s': "Tiempo (s)",
        'force_n': "Fuerza (N)",
        'elongation_mm': "Alargamiento (mm)",
        'stress_mpa': "Tensión (MPa)",
        'strain_perc': "Deformación (%)",
        'waiting_for_test': "Esperando inicio del ensayo...",
        'ready_for_new_test': "Listo para nuevo ensayo",
        'elongation_mm_axis': "Alargamiento (mm)",
        'force_n_axis': "Fuerza (N)",
        'compression_title': "Laboratorio Virtual: Compresión",
        'compression_subtitle': "Ensayos de Materiales",
        'specimen_config_comp': "1. Configuración de Probeta",
        'concrete_fragile': "Materiales de Construcción (Frágiles)",
        'pine_wood': "Madera de Pino",
        'concrete25': "Hormigón HA-25 (Convencional)",
        'concrete50': "Hormigón HA-50 (Alta Resistencia)",
        'mortar': "Mortero de Cemento (M-15)",
        'metals_ductile': "Metales (Dúctiles)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estándar (15x30 cm por defecto)",
        'start_compression': "Iniciar Compresión",
        'new_specimen': "Nueva Probeta",
        'press_chamber': "Prensa de Ensayos",
        'graph_title_comp': "2. Gráfica Tensión - Deformación",
        'graph_subtitle_comp': "Eje Y: Tensión (MPa) | Eje X: Acortamiento (%)",
        'data_acq_comp': "3. Registro de Datos",
        'data_subtitle_comp': "Valores negativos indican compresión (acortamiento).",
        'force_kn': "Fuerza (kN)",
        'shortening_mm': "Acortamiento (mm)",
        'system_ready': "Sistema preparado. Coloque probeta.",
        'pvc': "PVC Rígido",
        'flexion_title': "Laboratorio Virtual: Flexión",
        'flexion_subtitle': "Ensayo de Flexión en 3 Puntos (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta y Material",
        'select_material': "Selección de Material",
        'woods': "Maderas",
        'pine': "Madera de Pino (Conífera)",
        'oak': "Madera de Roble (Frondosa)",
        'ceramics_glass': "Cerámicos y Vidrio",
        'glass': "Vidrio (Frágil)",
        'ceramic_tile': "Baldosa Cerámica",
        'polymers': "Polímeros",
        'pmma': "Metacrilato (PMMA)",
        'pp': "Polipropileno (Muy flexible)",
        'span_l': "Luz ($L$) [mm]",
        'width_b': "Ancho ($b$) [mm]",
        'thickness_h': "Espesor ($h$) [mm]",
        'inertia_iz': "Momento de Inercia ($I_z$):",
        'flex_test_chamber': "Cámara de Ensayo",
        'load_f': "Carga (F)",
        'deflection_d': "Flecha (δ)",
        'graph_title_flex': "2. Gráfica Fuerza vs Flecha",
        'y_axis_force': "Eje Y: Fuerza (N)",
        'x_axis_deflection': "Eje X: Flecha (mm)",
        'data_acq_flex': "3. Registro de Datos",
        'flex_formulas': "Fórmulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Fuerza (N)",
        'deflection_mm_col': "Flecha (mm)",
        'stress_mpa_col': "Tensión (MPa)",
        'config_specimen_start': "Configura la probeta e inicia el ensayo.",
        'break_fragile': "¡ROTURA FRÁGIL!",
        'def_limit': "LÍMITE DEF.",
        'educational_bench': "1 kN (Banco Educativo)",
        'standard_lab_flexion': "10 kN (Estándar Laboratorio)",
        'high_capacity_flexion': "100 kN (Alta Capacidad)",
        'ready_new_test_flex': "Listo para nuevo ensayo.",
        'torsion_title': "Laboratorio Virtual: Torsión",
        'torsion_subtitle': "Ensayo de Torsión Simple (Materiales Metálicos)",
        'torsion_config': "1. Configuración del Ensayo",
        'ductile': "Dúctiles",
        'fragile': "Frágiles",
        'f114_steel': "Acero F-114 (Estructural)",
        'brass': "Latón (Aleación Cu-Zn)",
        'cast_iron': "Fundición Gris (Hierro Colado)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Momento Polar de Inercia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Sección maciza)",
        'start_rotation': "▶ Iniciar Giro",
        'torsion_bench': "Banco de Torsión",
        'torque': "PAR (Torque)",
        'angle_phi': "ÁNGULO (φ)",
        'graph_title_torsion': "2. Diagrama Momento - Ángulo",
        'y_axis_torque': "Y: Par Torsor (Nm)",
        'x_axis_angle': "X: Giro (rad)",
        'data_acq_torsion': "3. Registro de Datos",
        'shear_stress_formula': "Tensión cortante máx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Ángulo (°)",
        'angle_rad': "Ángulo (rad)",
        'machine_torque_limit': "Límite de Par de la Máquina",
        'small_bench': "100 Nm (Banco Pequeño)",
        'standard_lab_torsion': "1000 Nm (Estándar Laboratorio)",
        'high_capacity_torsion': "5000 Nm (Alta Capacidad)",
        'torque_nm': "Par (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en reposo. Configura probeta.",
        'ready': "Listo.",
        'fatigue_title': "Laboratorio Virtual: Fatiga",
        'fatigue_subtitle': "Ensayo de Carga Cíclica (Curva S-N)",
        'cyclic_load_params': "1. Parámetros de Carga Cíclica",
        'carbon_steel': "Acero al Carbono",
        'aluminum_alloy': "Aleación de Aluminio",
        'titanium_alloy': "Aleación de Titanio",
        'max_stress': "Tensión Máxima ($\\sigma_{max}$)",
        'stress_ratio': "Ratio de Tensiones (R = $\\sigma_{min} / \\sigma_{max}$)",
        'tension_compression': "Tracción-Compresión (R=-1)",
        'tension_tension': "Tracción-Tracción (R>0)",
        'mean_stress': "Tensión Media ($\\sigma_m$):",
        'stress_amplitude': "Amplitud de Tensión ($\\sigma_a$):",
        'cycle_count': "Número de Ciclos (N)",
        'current_stress': "Tensión Actual",
        'fatigue_failure': "FALLO POR FATIGA",
        'sn_diagram_title': "2. Diagrama S-N (Wöhler)",
        'sn_diagram_desc': "Representa la Amplitud de Tensión ($\\sigma_a$) frente al Número de Ciclos hasta el fallo (N). El eje X es logarítmico.",
        'objective': "Objetivo:",
        'objective_desc_fatigue': "Realiza ensayos a diferentes niveles de $\\sigma_a$ para construir la curva. Observarás que a menor tensión, el material aguanta muchos más ciclos antes de romperse.",
        'test_results': "3. Resultados de los Ensayos",
        'clear_graph': "Limpiar Gráfica",
        'stress_amplitude_col': "$\\sigma_a$ (MPa)",
        'ratio_r_col': "R",
        'cycles_n_col': "Ciclos (N)",
        'populate_graph': "Realiza ensayos para poblar la gráfica.",
        'data_cleared': "Datos borrados.",
        'stress_amplitude_axis': "Amplitud de Tensión, σa (MPa)",
        'cycles_to_failure_axis': "Ciclos hasta Fallo, N (escala log)",
        'resilience_title': "Laboratorio Virtual: Resiliencia",
        'resilience_subtitle': "Ensayo de Impacto Charpy (ISO 148-1)",
        'sample_prep': "1. Preparación de la Muestra",
        'low_carbon_steel': "Acero Bajo Carbono (S235)",
        'tempered_steel_desc': "Más frágil, menor energía máxima.",
        'fcc_desc': "Red FCC: No presenta transición drástica.",
        'hcp_desc': "Alta tenacidad, curva suave.",
        'pendulum_params': "Parámetros del Péndulo",
        'pendulum_mass': "Masa del Péndulo",
        'arm_length': "Longitud del Brazo",
        'initial_energy': "Energía Potencial Inicial:",
        'high_carbon_steel': "Acero Alto Carbono (Templado)",
        'aluminum_alloy_7075': "Aleación Aluminio (7075)",
        'titanium_alloy_ti64': "Titanio (Ti-6Al-4V)",
        'bcc_desc_initial': "Presenta transición dúctil-frágil clara.",
        'test_temp': "Temperatura de Ensayo",
        'temp_n2': "-100°C (N₂)",
        'temp_100': "+100°C",
        'release_pendulum': "Soltar Péndulo",
        'new_specimen_charpy': "Nueva Probeta",
        'impact_chamber': "Cámara de Impacto",
        'energy_kv': "ENERGÍA (KV)",
        'transition_curve_title': "2. Curva de Transición Dúctil-Frágil",
        'transition_curve_desc': "Realice ensayos a distintas temperaturas para construir la curva.",
        'impact_log': "3. Registro de Impactos",
        'resilience_formula': "Resiliencia $\\rho = KCV / S_0$ (J/cm²)",
        'clear_data': "Borrar Datos",
        'material_col': "Material",
        'temp_col': "Temp (°C)",
        'energy_col': "Energía (J)",
        'fracture_type_col': "Rotura",
        'add_points_temp': "Añada puntos ensayando a diferentes temperaturas.",
        'help_elastic_zone': "Zona Elástica: El material se deforma pero vuelve a su forma original si se retira la carga. La pendiente de esta recta es el Módulo de Young (E).", // Aquesta clau ja existia
        'initial_height': "Altura Inicial:",
        'final_height': "Altura Final:",
        'help_yield_point': "Límite Elástico (Fluencia): Punto donde el material empieza a deformarse plásticamente (de forma permanente).",
        'help_plastic_zone': "Zona Plástica: El material sufre una deformación permanente. Aunque se retire la carga, no recuperará su forma inicial."
    },
    'en': { // Anglès
        'main_title': "Virtual Materials Testing Laboratory",
        'main_subtitle': "Interactive simulations for Vocational Training",
        'select_test': "Select a Test to Begin",
        'tensile_test': "Tensile Test",
        'tensile_desc': "Simulates stretching a specimen to failure to obtain the Force-Elongation diagram.",
        'compression_test': "Compression Test",
        'compression_desc': "Simulates the compression of a specimen, typically concrete, until it collapses.",
        'flexion_test': "Flexion (Bending) Test",
        'flexion_desc': "Simulates a three-point bending test on a simple beam to determine its strength.",
        'torsion_test': "Torsion Test",
        'torsion_desc': "Simulates twisting a shaft to failure, obtaining the Torque-Angle diagram.",
        'resilience_test': "Resilience Test",
        'resilience_desc': "Simulates the Charpy pendulum impact test to study the ductile-brittle transition.",
        'fatigue_test': "Fatigue Test",
        'fatigue_desc': "Simulates cyclic loading to determine the service life of a material (S-N Curve).",
        'return_to_menu': "Return to menu",
        'traction_title': "Virtual Lab: Tensile Test",
        'traction_subtitle': "Uniaxial Tensile Test",
        'specimen_config': "1. Specimen Configuration",
        'material': "Material",
        'machine_limit': "Machine Force Limit",
        'steel': "Structural Steel (S275)",
        'aluminum': "Aluminum Alloy (6061)",
        'copper': "Annealed Copper",
        'polymer': "Rigid Polymer (PVC)",
        'length': "Length ($L_0$) [mm]",
        'diameter': "Diameter ($D_0$) [mm]",
        'area': "Area",
        'start_test': "Start Test",
        'reset': "Reset",
        'test_chamber': "Test Chamber",
        'current_load': "Current Load",
        'graph_title_traction': "2. Force - Elongation Diagram",
        'real_time_sim': "Real-time simulation",
        'data_acquisition': "3. Data Acquisition",
        'data_subtitle_traction': "Raw data from the load cell and extensometer.",
        'download_csv': "Download CSV",
        'time_s': "Time (s)",
        'force_n': "Force (N)",
        'elongation_mm': "Elongation (mm)",
        'stress_mpa': "Stress (MPa)",
        'strain_perc': "Strain (%)",
        'waiting_for_test': "Waiting for test to start...",
        'ready_for_new_test': "Ready for new test",
        'elongation_mm_axis': "Elongation (mm)",
        'force_n_axis': "Force (N)",
        'compression_title': "Virtual Lab: Compression",
        'compression_subtitle': "Materials Testing",
        'specimen_config_comp': "1. Specimen Configuration",
        'concrete_fragile': "Construction Materials (Brittle)",
        'pine_wood': "Pine Wood",
        'concrete25': "Concrete HA-25 (Conventional)",
        'concrete50': "Concrete HA-50 (High-Strength)",
        'mortar': "Cement Mortar (M-15)",
        'metals_ductile': "Metals (Ductile)",
        'height': "Height ($H_0$) [mm]",
        'std_specimen_comp': "* Standard Cylindrical Specimen (15x30 cm by default)",
        'start_compression': "Start Compression",
        'new_specimen': "New Specimen",
        'press_chamber': "Testing Press",
        'graph_title_comp': "2. Stress - Strain Graph",
        'graph_subtitle_comp': "Y-axis: Stress (MPa) | X-axis: Shortening (%)",
        'data_acq_comp': "3. Data Log",
        'data_subtitle_comp': "Negative values indicate compression (shortening).",
        'force_kn': "Force (kN)",
        'shortening_mm': "Shortening (mm)",
        'system_ready': "System ready. Place specimen.",
        'pvc': "Rigid PVC",
        'flexion_title': "Virtual Lab: Bending",
        'flexion_subtitle': "3-Point Bending Test (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Specimen and Material",
        'select_material': "Material Selection",
        'woods': "Woods",
        'pine': "Pine Wood (Softwood)",
        'oak': "Oak Wood (Hardwood)",
        'ceramics_glass': "Ceramics & Glass",
        'glass': "Glass (Brittle)",
        'ceramic_tile': "Ceramic Tile",
        'polymers': "Polymers",
        'pmma': "Acrylic (PMMA)",
        'pp': "Polypropylene (Very flexible)",
        'span_l': "Span ($L$) [mm]",
        'width_b': "Width ($b$) [mm]",
        'thickness_h': "Thickness ($h$) [mm]",
        'inertia_iz': "Moment of Inertia ($I_z$):",
        'flex_test_chamber': "Test Chamber",
        'load_f': "Load (F)",
        'deflection_d': "Deflection (δ)",
        'graph_title_flex': "2. Force vs Deflection Graph",
        'y_axis_force': "Y-axis: Force (N)",
        'x_axis_deflection': "X-axis: Deflection (mm)",
        'data_acq_flex': "3. Data Log",
        'flex_formulas': "Formulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Force (N)",
        'deflection_mm_col': "Deflection (mm)",
        'stress_mpa_col': "Stress (MPa)",
        'config_specimen_start': "Configure the specimen and start the test.",
        'break_fragile': "BRITTLE FAILURE!",
        'def_limit': "DEF. LIMIT",
        'educational_bench': "1 kN (Educational Bench)",
        'standard_lab_flexion': "10 kN (Standard Lab)",
        'high_capacity_flexion': "100 kN (High Capacity)",
        'ready_new_test_flex': "Ready for new test.",
        'torsion_title': "Virtual Lab: Torsion",
        'torsion_subtitle': "Simple Torsion Test (Metallic Materials)",
        'torsion_config': "1. Test Configuration",
        'ductile': "Ductile",
        'fragile': "Brittle",
        'f114_steel': "F-114 Steel (Structural)",
        'brass': "Brass (Cu-Zn Alloy)",
        'cast_iron': "Gray Cast Iron",
        'nylon': "Nylon (Polyamide)",
        'polar_moment': "Polar Moment of Inertia ($J$):",
        'polar_moment_formula': "Formula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Solid section)",
        'start_rotation': "▶ Start Rotation",
        'torsion_bench': "Torsion Bench",
        'torque': "TORQUE",
        'angle_phi': "ANGLE (φ)",
        'graph_title_torsion': "2. Torque - Angle Diagram",
        'y_axis_torque': "Y: Torque (Nm)",
        'x_axis_angle': "X: Angle (rad)",
        'data_acq_torsion': "3. Data Log",
        'shear_stress_formula': "Max shear stress: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angle (°)",
        'angle_rad': "Angle (rad)",
        'machine_torque_limit': "Machine Torque Limit",
        'small_bench': "100 Nm (Small Bench)",
        'standard_lab_torsion': "1000 Nm (Standard Lab)",
        'high_capacity_torsion': "5000 Nm (High Capacity)",
        'torque_nm': "Torque (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "System idle. Configure specimen.",
        'ready': "Ready.",
        'fatigue_title': "Virtual Lab: Fatigue",
        'fatigue_subtitle': "Cyclic Loading Test (S-N Curve)",
        'cyclic_load_params': "1. Cyclic Loading Parameters",
        'carbon_steel': "Carbon Steel",
        'aluminum_alloy': "Aluminum Alloy",
        'titanium_alloy': "Titanium Alloy",
        'max_stress': "Maximum Stress ($\\sigma_{max}$)",
        'stress_ratio': "Stress Ratio (R = $\\sigma_{min} / \\sigma_{max}$)",
        'tension_compression': "Tension-Compression (R=-1)",
        'tension_tension': "Tension-Tension (R>0)",
        'mean_stress': "Mean Stress ($\\sigma_m$):",
        'stress_amplitude': "Stress Amplitude ($\\sigma_a$):",
        'cycle_count': "Number of Cycles (N)",
        'current_stress': "Current Stress",
        'fatigue_failure': "FATIGUE FAILURE",
        'sn_diagram_title': "2. S-N Diagram (Wöhler)",
        'sn_diagram_desc': "Represents the Stress Amplitude ($\\sigma_a$) versus the Number of Cycles to failure (N). The X-axis is logarithmic.",
        'objective': "Objective:",
        'objective_desc_fatigue': "Perform tests at different $\\sigma_a$ levels to build the curve. You will notice that at lower stress, the material withstands many more cycles before breaking.",
        'test_results': "3. Test Results",
        'clear_graph': "Clear Graph",
        'stress_amplitude_col': "$\\sigma_a$ (MPa)",
        'ratio_r_col': "R",
        'cycles_n_col': "Cycles (N)",
        'populate_graph': "Perform tests to populate the graph.",
        'data_cleared': "Data cleared.",
        'stress_amplitude_axis': "Stress Amplitude, σa (MPa)",
        'cycles_to_failure_axis': "Cycles to Failure, N (log scale)",
        'resilience_title': "Virtual Lab: Resilience",
        'resilience_subtitle': "Charpy Impact Test (ISO 148-1)",
        'sample_prep': "1. Sample Preparation",
        'low_carbon_steel': "Low Carbon Steel (S235)",
        'tempered_steel_desc': "More brittle, lower maximum energy.",
        'fcc_desc': "FCC lattice: No drastic transition.",
        'hcp_desc': "High toughness, smooth curve.",
        'pendulum_params': "Pendulum Parameters",
        'pendulum_mass': "Pendulum Mass",
        'arm_length': "Arm Length",
        'initial_energy': "Initial Potential Energy:",
        'high_carbon_steel': "High Carbon Steel (Hardened)",
        'aluminum_alloy_7075': "Aluminum Alloy (7075)",
        'titanium_alloy_ti64': "Titanium (Ti-6Al-4V)",
        'bcc_desc_initial': "Shows a clear ductile-brittle transition.",
        'test_temp': "Test Temperature",
        'temp_n2': "-100°C (N₂)",
        'temp_100': "+100°C",
        'release_pendulum': "Release Pendulum",
        'new_specimen_charpy': "New Specimen",
        'impact_chamber': "Impact Chamber",
        'energy_kv': "ENERGY (KV)",
        'transition_curve_title': "2. Ductile-Brittle Transition Curve",
        'transition_curve_desc': "Perform tests at different temperatures to build the curve.",
        'impact_log': "3. Impact Log",
        'resilience_formula': "Resilience $\\rho = KCV / S_0$ (J/cm²)",
        'clear_data': "Clear Data",
        'material_col': "Material",
        'temp_col': "Temp (°C)",
        'energy_col': "Energy (J)",
        'fracture_type_col': "Fracture",
        'add_points_temp': "Add points by testing at different temperatures.",
        'help_elastic_zone': "Elastic Zone: The material deforms but returns to its original shape if the load is removed. The slope of this line is the Young's Modulus (E).", // Aquesta clau ja existia
        'initial_height': "Initial Height:",
        'final_height': "Final Height:",
        'help_yield_point': "Yield Point: The point where the material begins to deform plastically (permanently).",
        'help_plastic_zone': "Plastic Zone: The material undergoes permanent deformation. Even if the load is removed, it will not regain its initial shape."
    },
    'eu': { // Basc
        'main_title': "Materialen Saiakuntzen Laborategi Birtuala",
        'main_subtitle': "Lanbide Heziketarako simulazio interaktiboak",
        'select_test': "Hautatu Saiakuntza bat Hasteko",
        'tensile_test': "Trakzio Saiakuntza",
        'tensile_desc': "Probeta baten luzapena simulatzen du, hausturara iritsi arte, Indar-Luzapen diagrama lortzeko.",
        'compression_test': "Konpresio Saiakuntza",
        'compression_desc': "Probeta baten konpresioa simulatzen du, normalean hormigoia, kolapsatu arte.",
        'flexion_test': "Makurdura Saiakuntza",
        'flexion_desc': "Hiru puntuko makurdura-saiakuntza simulatzen du habe sinple batean, haren erresistentzia zehazteko.",
        'torsion_test': "Tortsio Saiakuntza",
        'torsion_desc': "Ardatz baten tortsioa simulatzen du, hausturara iritsi arte, Momentu-Angelu diagrama lortuz.",
        'resilience_test': "Erresilientzia Saiakuntza",
        'resilience_desc': "Charpy penduluaren talka-saiakuntza simulatzen du, trantsizio harikor-hauskorra aztertzeko.",
        'fatigue_test': "Neke Saiakuntza",
        'fatigue_desc': "Karga ziklikoen aplikazioa simulatzen du material baten bizitza erabilgarria zehazteko (S-N Kurba).",
        'return_to_menu': "Itzuli menura",
        'traction_title': "Laborategi Birtuala: Trakzioa",
        'traction_subtitle': "Trakzio Uniaxialeko Saiakuntza",
        'specimen_config': "1. Probetaren Konfigurazioa",
        'material': "Materiala",
        'machine_limit': "Makinaren Indar Muga",
        'steel': "Egiturazko Altzairua (S275)",
        'aluminum': "Aluminio Aleazioa (6061)",
        'copper': "Kobre Egosia",
        'polymer': "Polimero Zurruna (PVC)",
        'length': "Luzera ($L_0$) [mm]",
        'diameter': "Diametroa ($D_0$) [mm]",
        'area': "Azalera",
        'start_test': "Hasi Saiakuntza",
        'reset': "Berrezarri",
        'test_chamber': "Saiakuntza-ganbera",
        'current_load': "Uneko Karga",
        'graph_title_traction': "2. Indar - Luzapen Diagrama",
        'real_time_sim': "Denbora errealeko simulazioa",
        'data_acquisition': "3. Datu-bilketa",
        'data_subtitle_traction': "Karga-sentsoretik eta estentsometrotik lortutako datu gordinak.",
        'download_csv': "Deskargatu CSV",
        'time_s': "Denbora (s)",
        'force_n': "Indarra (N)",
        'elongation_mm': "Luzapena (mm)",
        'stress_mpa': "Tentsioa (MPa)",
        'strain_perc': "Deformazioa (%)",
        'waiting_for_test': "Saiakuntza noiz hasiko zain...",
        'ready_for_new_test': "Saiakuntza berrirako prest",
        'elongation_mm_axis': "Luzapena (mm)",
        'force_n_axis': "Indarra (N)",
        'compression_title': "Laborategi Birtuala: Konpresioa",
        'compression_subtitle': "Materialen Saiakuntzak",
        'specimen_config_comp': "1. Probetaren Konfigurazioa",
        'concrete_fragile': "Eraikuntzako Materialak (Hauskorrak)",
        'pine_wood': "Pinu-zura",
        'concrete25': "Hormigoi HA-25 (Ohikoa)",
        'concrete50': "Hormigoi HA-50 (Erresistentzia Handikoa)",
        'mortar': "Zementuzko Morteroa (M-15)",
        'metals_ductile': "Metalak (Harikorrak)",
        'height': "Altuera ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Zilindriko Estandarra (15x30 cm lehenetsita)",
        'start_compression': "Hasi Konpresioa",
        'new_specimen': "Probeta Berria",
        'press_chamber': "Saiakuntza Prentsa",
        'graph_title_comp': "2. Tentsio - Deformazio Grafikoa",
        'graph_subtitle_comp': "Y ardatza: Tentsioa (MPa) | X ardatza: Laburtzea (%)",
        'data_acq_comp': "3. Datuen Erregistroa",
        'data_subtitle_comp': "Balio negatiboek konpresioa (laburtzea) adierazten dute.",
        'force_kn': "Indarra (kN)",
        'shortening_mm': "Laburtzea (mm)",
        'system_ready': "Sistema prest. Jarri probeta.",
        'pvc': "PVC Zurruna",
        'flexion_title': "Laborategi Birtuala: Makurdura",
        'flexion_subtitle': "3 Puntuko Makurdura Saiakuntza (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta eta Materiala",
        'select_material': "Materiala Aukeratu",
        'woods': "Egurrak",
        'pine': "Pinu-zura (Koniferoa)",
        'oak': "Haritz-zura (Hostozabala)",
        'ceramics_glass': "Zeramikak eta Beira",
        'glass': "Beira (Hauskorra)",
        'ceramic_tile': "Zeramikazko Laukia",
        'polymers': "Polimeroak",
        'pmma': "Metakrilatoa (PMMA)",
        'pp': "Polipropilenoa (Oso malgua)",
        'span_l': "Argi-zuloa ($L$) [mm]",
        'width_b': "Zabalera ($b$) [mm]",
        'thickness_h': "Lodiera ($h$) [mm]",
        'inertia_iz': "Inertzia Momentua ($I_z$):",
        'flex_test_chamber': "Saiakuntza Ganbera",
        'load_f': "Karga (F)",
        'deflection_d': "Gezi (δ)",
        'graph_title_flex': "2. Indarra vs Gezi Grafikoa",
        'y_axis_force': "Y ardatza: Indarra (N)",
        'x_axis_deflection': "X ardatza: Gezia (mm)",
        'data_acq_flex': "3. Datuen Erregistroa",
        'flex_formulas': "Formulak: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Indarra (N)",
        'deflection_mm_col': "Gezia (mm)",
        'stress_mpa_col': "Tentsioa (MPa)",
        'config_specimen_start': "Konfiguratu probeta eta hasi saiakuntza.",
        'break_fragile': "HAUSTURA HAUSKORRA!",
        'def_limit': "DEF. MUGA",
        'educational_bench': "1 kN (Hezkuntza Bankua)",
        'standard_lab_flexion': "10 kN (Laborategi Estandarra)",
        'high_capacity_flexion': "100 kN (Gaitasun Handia)",
        'ready_new_test_flex': "Saiakuntza berrirako prest.",
        'torsion_title': "Laborategi Birtuala: Tortsioa",
        'torsion_subtitle': "Tortsio Saiakuntza Sinplea (Material Metalikoak)",
        'torsion_config': "1. Saiakuntzaren Konfigurazioa",
        'ductile': "Harikorrak",
        'fragile': "Hauskorrak",
        'f114_steel': "F-114 Altzairua (Egiturazkoa)",
        'brass': "Letoia (Cu-Zn Aleazioa)",
        'cast_iron': "Burdinurtu Grisa",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Inertzia Momentu Polarra ($J$):",
        'polar_moment_formula': "Formula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Atal trinkoa)",
        'start_rotation': "▶ Hasi Biraketa",
        'torsion_bench': "Tortsio Bankua",
        'torque': "BIHURDURA",
        'angle_phi': "ANGELUA (φ)",
        'graph_title_torsion': "2. Momentu - Angelu Diagrama",
        'y_axis_torque': "Y: Momentu Bihurtzailea (Nm)",
        'x_axis_angle': "X: Biraketa (rad)",
        'data_acq_torsion': "3. Datuen Erregistroa",
        'shear_stress_formula': "Ebakidura-tentsio max: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Angelua (°)",
        'angle_rad': "Angelua (rad)",
        'machine_torque_limit': "Makinaren Pare Muga",
        'small_bench': "100 Nm (Banku Txikia)",
        'standard_lab_torsion': "1000 Nm (Laborategi Estandarra)",
        'high_capacity_torsion': "5000 Nm (Gaitasun Handia)",
        'torque_nm': "Momentua (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema geldirik. Konfiguratu probeta.",
        'ready': "Prest.",
        'fatigue_title': "Laborategi Birtuala: Nekea",
        'fatigue_subtitle': "Karga Ziklikoko Saiakuntza (S-N Kurba)",
        'cyclic_load_params': "1. Karga Ziklikoaren Parametroak",
        'carbon_steel': "Karbono Altzairua",
        'aluminum_alloy': "Aluminio Aleazioa",
        'titanium_alloy': "Titanio Aleazioa",
        'max_stress': "Tentsio Maximoa ($\\sigma_{max}$)",
        'stress_ratio': "Tentsio Arrazoia (R = $\\sigma_{min} / \\sigma_{max}$)",
        'tension_compression': "Trakzio-Konpresioa (R=-1)",
        'tension_tension': "Trakzio-Trakzioa (R>0)",
        'mean_stress': "Batez besteko Tentsioa ($\\sigma_m$):",
        'stress_amplitude': "Tentsio Anplitudea ($\\sigma_a$):",
        'cycle_count': "Ziklo Kopurua (N)",
        'current_stress': "Uneko Tentsioa",
        'fatigue_failure': "NEKEAGATIKO HAUSTURA",
        'sn_diagram_title': "2. S-N Diagrama (Wöhler)",
        'sn_diagram_desc': "Tentsio Anplitudea ($\\sigma_a$) eta hausturara arteko Ziklo Kopuruaren (N) arteko erlazioa adierazten du. X ardatza logaritmikoa da.",
        'objective': "Helburua:",
        'objective_desc_fatigue': "Egin saiakuntzak $\\sigma_a$ maila desberdinetan kurba eraikitzeko. Tentsio txikiagoarekin, materialak ziklo gehiago jasaten dituela ikusiko duzu hautsi aurretik.",
        'test_results': "3. Saiakuntzen Emaitzak",
        'clear_graph': "Garbitu Grafikoa",
        'stress_amplitude_col': "$\\sigma_a$ (MPa)",
        'ratio_r_col': "R",
        'cycles_n_col': "Zikloak (N)",
        'populate_graph': "Egin saiakuntzak grafikoa betetzeko.",
        'data_cleared': "Datuak ezabatuta.",
        'stress_amplitude_axis': "Tentsio Anplitudea, σa (MPa)",
        'cycles_to_failure_axis': "Zikloak Hausturara, N (eskala log)",
        'resilience_title': "Laborategi Birtuala: Erresilientzia",
        'resilience_subtitle': "Charpy Talka Saiakuntza (ISO 148-1)",
        'sample_prep': "1. Laginaren Prestaketa",
        'low_carbon_steel': "Karbono Gutxiko Altzairua (S235)",
        'tempered_steel_desc': "Hauskorragoa, energia maximo txikiagoa.",
        'fcc_desc': "FCC sarea: Ez du trantsizio nabarmenik.",
        'hcp_desc': "Sendotasun handia, kurba leuna.",
        'pendulum_params': "Penduluaren Parametroak",
        'pendulum_mass': "Penduluaren Masa",
        'arm_length': "Besoaren Luzera",
        'initial_energy': "Hasierako Energia Potentziala:",
        'high_carbon_steel': "Karbono Handiko Altzairua (Gogortua)",
        'aluminum_alloy_7075': "Aluminio Aleazioa (7075)",
        'titanium_alloy_ti64': "Titanioa (Ti-6Al-4V)",
        'bcc_desc_initial': "Trantsizio harikor-hauskor argia du.",
        'test_temp': "Saiakuntzaren Tenperatura",
        'temp_n2': "-100°C (N₂)",
        'temp_100': "+100°C",
        'release_pendulum': "Askatu Pendulua",
        'new_specimen_charpy': "Probeta Berria",
        'impact_chamber': "Talka Ganbera",
        'energy_kv': "ENERGIA (KV)",
        'transition_curve_title': "2. Trantsizio Harikor-Hauskorraren Kurba",
        'transition_curve_desc': "Egin saiakuntzak tenperatura desberdinetan kurba eraikitzeko.",
        'impact_log': "3. Talken Erregistroa",
        'resilience_formula': "Erresilientzia $\\rho = KCV / S_0$ (J/cm²)",
        'clear_data': "Ezabatu Datuak",
        'material_col': "Materiala",
        'temp_col': "Tenp (°C)",
        'energy_col': "Energia (J)",
        'fracture_type_col': "Haustura",
        'add_points_temp': "Gehitu puntuak tenperatura desberdinetan saiatuz.",
        'help_elastic_zone': "Eremu Elastikoa: Materiala deformatu egiten da, baina jatorrizko formara itzultzen da karga kentzen bada. Lerro honen malda Young-en Modulua (E) da.", // Aquesta clau ja existia
        'initial_height': "Hasierako Altuera:",
        'final_height': "Amaierako Altuera:",
        'help_yield_point': "Muga Elastikoa (Isurpena): Materiala plastikoki (betirako) deformatzen hasten den puntua.",
        'help_plastic_zone': "Eremu Plastikoa: Materialak deformazio iraunkorra jasaten du. Karga kenduta ere, ez du hasierako forma berreskuratuko."
    },
    'gl': { // Gallec
        'main_title': "Laboratorio Virtual de Ensaios de Materiais",
        'main_subtitle': "Simulacións interactivas para Formación Profesional",
        'select_test': "Selecciona un Ensaio para Comezar",
        'tensile_test': "Ensaio de Tracción",
        'tensile_desc': "Simula o estiramento dunha probeta ata a súa fractura para obter o diagrama Forza-Alongamento.",
        'compression_test': "Ensaio de Compresión",
        'compression_desc': "Simula a compresión dunha probeta, normalmente de formigón, ata o seu colapso.",
        'flexion_test': "Ensaio de Flexión",
        'flexion_desc': "Simula un ensaio de flexión en tres puntos sobre unha viga simple para determinar a súa resistencia.",
        'torsion_test': "Ensaio de Torsión",
        'torsion_desc': "Simula a torsión dun eixe ata a súa fractura, obtendo o diagrama Momento-Ángulo.",
        'resilience_test': "Ensaio de Resiliencia",
        'resilience_desc': "Simula o ensaio de impacto co Péndulo de Charpy para estudar a transición dúctil-fráxil.",
        'fatigue_test': "Ensaio de Fatiga",
        'fatigue_desc': "Simula a aplicación de cargas cíclicas para determinar a vida útil dun material (Curva S-N).",
        'return_to_menu': "Volver ao menú",
        'traction_title': "Laboratorio Virtual: Tracción",
        'traction_subtitle': "Ensaio de Tracción Uniaxial",
        'specimen_config': "1. Configuración da Probeta",
        'material': "Material",
        'machine_limit': "Límite de Forza da Máquina",
        'steel': "Aceiro Estrutural (S275)",
        'aluminum': "Aliaxe de Aluminio (6061)",
        'copper': "Cobre Recocido",
        'polymer': "Polímero Ríxido (PVC)",
        'length': "Lonxitude ($L_0$) [mm]",
        'diameter': "Diámetro ($D_0$) [mm]",
        'area': "Área",
        'start_test': "Iniciar Ensaio",
        'reset': "Reset",
        'test_chamber': "Cámara de ensaios",
        'current_load': "Carga Actual",
        'graph_title_traction': "2. Diagrama Forza - Alongamento",
        'real_time_sim': "Simulación en tempo real",
        'data_acquisition': "3. Adquisición de Datos",
        'data_subtitle_traction': "Datos crus obtidos do sensor de carga e o extensómetro.",
        'download_csv': "Descargar CSV",
        'time_s': "Tempo (s)",
        'force_n': "Forza (N)",
        'elongation_mm': "Alongamento (mm)",
        'stress_mpa': "Tensión (MPa)",
        'strain_perc': "Deformación (%)",
        'waiting_for_test': "Agardando inicio do ensaio...",
        'ready_for_new_test': "Listo para novo ensaio",
        'elongation_mm_axis': "Alongamento (mm)",
        'force_n_axis': "Forza (N)",
        'compression_title': "Laboratorio Virtual: Compresión",
        'compression_subtitle': "Ensaios de Materiais",
        'specimen_config_comp': "1. Configuración da Probeta",
        'concrete_fragile': "Materiais de Construción (Fráxiles)",
        'pine_wood': "Madeira de Piñeiro",
        'concrete25': "Formigón HA-25 (Convencional)",
        'concrete50': "Formigón HA-50 (Alta Resistencia)",
        'mortar': "Morteiro de Cemento (M-15)",
        'metals_ductile': "Metais (Dúctiles)",
        'height': "Altura ($H_0$) [mm]",
        'std_specimen_comp': "* Probeta Cilíndrica Estándar (15x30 cm por defecto)",
        'start_compression': "Iniciar Compresión",
        'new_specimen': "Nova Probeta",
        'press_chamber': "Prensa de Ensaios",
        'graph_title_comp': "2. Gráfica Tensión - Deformación",
        'graph_subtitle_comp': "Eixo Y: Tensión (MPa) | Eixo X: Acurtamento (%)",
        'data_acq_comp': "3. Rexistro de Datos",
        'data_subtitle_comp': "Valores negativos indican compresión (acurtamento).",
        'force_kn': "Forza (kN)",
        'shortening_mm': "Acurtamento (mm)",
        'system_ready': "Sistema preparado. Coloque a probeta.",
        'pvc': "PVC Ríxido",
        'flexion_title': "Laboratorio Virtual: Flexión",
        'flexion_subtitle': "Ensaio de Flexión en 3 Puntos (UNE-EN ISO 178 / 14125)",
        'specimen_mat_flex': "1. Probeta e Material",
        'select_material': "Selección de Material",
        'woods': "Madeiras",
        'pine': "Madeira de Piñeiro (Conífera)",
        'oak': "Madeira de Carballo (Frondosa)",
        'ceramics_glass': "Cerámicos e Vidro",
        'glass': "Vidro (Fráxil)",
        'ceramic_tile': "Baldosa Cerámica",
        'polymers': "Polímeros",
        'pmma': "Metacrilato (PMMA)",
        'pp': "Polipropileno (Moi flexible)",
        'span_l': "Luz ($L$) [mm]",
        'width_b': "Ancho ($b$) [mm]",
        'thickness_h': "Espesor ($h$) [mm]",
        'inertia_iz': "Momento de Inercia ($I_z$):",
        'flex_test_chamber': "Cámara de Ensaio",
        'load_f': "Carga (F)",
        'deflection_d': "Frecha (δ)",
        'graph_title_flex': "2. Gráfica Forza vs Frecha",
        'y_axis_force': "Eixo Y: Forza (N)",
        'x_axis_deflection': "Eixo X: Frecha (mm)",
        'data_acq_flex': "3. Rexistro de Datos",
        'flex_formulas': "Fórmulas: $\\sigma_f = \\frac{3FL}{2bh^2}$ | $\\epsilon_f = \\frac{6h\\delta}{L^2}$",
        'force_n_col': "Forza (N)",
        'deflection_mm_col': "Frecha (mm)",
        'stress_mpa_col': "Tensión (MPa)",
        'config_specimen_start': "Configura a probeta e inicia o ensaio.",
        'break_fragile': "ROTURA FRÁXIL!",
        'def_limit': "LÍMITE DEF.",
        'educational_bench': "1 kN (Banco Educativo)",
        'standard_lab_flexion': "10 kN (Estándar Laboratorio)",
        'high_capacity_flexion': "100 kN (Alta Capacidade)",
        'ready_new_test_flex': "Listo para novo ensaio.",
        'torsion_title': "Laboratorio Virtual: Torsión",
        'torsion_subtitle': "Ensaio de Torsión Simple (Materiais Metálicos)",
        'torsion_config': "1. Configuración do Ensaio",
        'ductile': "Dúctiles",
        'fragile': "Fráxiles",
        'f114_steel': "Aceiro F-114 (Estrutural)",
        'brass': "Latón (Aliaxe Cu-Zn)",
        'cast_iron': "Fundición Gris (Ferro Fundido)",
        'nylon': "Nylon (Poliamida)",
        'polar_moment': "Momento Polar de Inercia ($J$):",
        'polar_moment_formula': "Fórmula: $J = \\frac{\\pi \\cdot D^4}{32}$ (Sección maciza)",
        'start_rotation': "▶ Iniciar Xiro",
        'torsion_bench': "Banco de Torsión",
        'torque': "PAR (Torque)",
        'angle_phi': "ÁNGULO (φ)",
        'graph_title_torsion': "2. Diagrama Momento - Ángulo",
        'y_axis_torque': "Y: Par Torsor (Nm)",
        'x_axis_angle': "X: Xiro (rad)",
        'data_acq_torsion': "3. Rexistro de Datos",
        'shear_stress_formula': "Tensión cortante máx: $\\tau = \\frac{16 T}{\\pi D^3}$",
        'angle_deg': "Ángulo (°)",
        'angle_rad': "Ángulo (rad)",
        'machine_torque_limit': "Límite de Par da Máquina",
        'small_bench': "100 Nm (Banco Pequeno)",
        'standard_lab_torsion': "1000 Nm (Estándar Laboratorio)",
        'high_capacity_torsion': "5000 Nm (Alta Capacidade)",
        'torque_nm': "Par (Nm)",
        'shear_stress_mpa': "τ (MPa)",
        'system_idle': "Sistema en repouso. Configura probeta.",
        'ready': "Listo.",
        'fatigue_title': "Laboratorio Virtual: Fatiga",
        'fatigue_subtitle': "Ensaio de Carga Cíclica (Curva S-N)",
        'cyclic_load_params': "1. Parámetros de Carga Cíclica",
        'carbon_steel': "Aceiro ao Carbono",
        'aluminum_alloy': "Aliaxe de Aluminio",
        'titanium_alloy': "Aliaxe de Titanio",
        'max_stress': "Tensión Máxima ($\\sigma_{max}$)",
        'stress_ratio': "Ratio de Tensións (R = $\\sigma_{min} / \\sigma_{max}$)",
        'tension_compression': "Tracción-Compresión (R=-1)",
        'tension_tension': "Tracción-Tracción (R>0)",
        'mean_stress': "Tensión Media ($\\sigma_m$):",
        'stress_amplitude': "Amplitude de Tensión ($\\sigma_a$):",
        'cycle_count': "Número de Ciclos (N)",
        'current_stress': "Tensión Actual",
        'fatigue_failure': "FALLO POR FATIGA",
        'sn_diagram_title': "2. Diagrama S-N (Wöhler)",
        'sn_diagram_desc': "Representa a Amplitude de Tensión ($\\sigma_a$) fronte ao Número de Ciclos ata o fallo (N). O eixo X é logarítmico.",
        'objective': "Obxectivo:",
        'objective_desc_fatigue': "Realiza ensaios a diferentes niveis de $\\sigma_a$ para construír a curva. Observarás que a menor tensión, o material aguanta moitos máis ciclos antes de romper.",
        'test_results': "3. Resultados dos Ensaios",
        'clear_graph': "Limpar Gráfica",
        'stress_amplitude_col': "$\\sigma_a$ (MPa)",
        'ratio_r_col': "R",
        'cycles_n_col': "Ciclos (N)",
        'populate_graph': "Realiza ensaios para poboar a gráfica.",
        'data_cleared': "Datos borrados.",
        'stress_amplitude_axis': "Amplitude de Tensión, σa (MPa)",
        'cycles_to_failure_axis': "Ciclos ata o Fallo, N (escala log)",
        'resilience_title': "Laboratorio Virtual: Resiliencia",
        'resilience_subtitle': "Ensaio de Impacto Charpy (ISO 148-1)",
        'sample_prep': "1. Preparación da Mostra",
        'low_carbon_steel': "Aceiro Baixo Carbono (S235)",
        'tempered_steel_desc': "Máis fráxil, menor enerxía máxima.",
        'fcc_desc': "Rede FCC: Non presenta transición drástica.",
        'hcp_desc': "Alta tenacidade, curva suave.",
        'pendulum_params': "Parámetros do Péndulo",
        'pendulum_mass': "Masa do Péndulo",
        'arm_length': "Lonxitude do Brazo",
        'initial_energy': "Enerxía Potencial Inicial:",
        'high_carbon_steel': "Aceiro Alto Carbono (Temperado)",
        'aluminum_alloy_7075': "Aliaxe de Aluminio (7075)",
        'titanium_alloy_ti64': "Titanio (Ti-6Al-4V)",
        'bcc_desc_initial': "Presenta unha clara transición dúctil-fráxil.",
        'test_temp': "Temperatura de Ensaio",
        'temp_n2': "-100°C (N₂)",
        'temp_100': "+100°C",
        'release_pendulum': "Soltar Péndulo",
        'new_specimen_charpy': "Nova Probeta",
        'impact_chamber': "Cámara de Impacto",
        'energy_kv': "ENERXÍA (KV)",
        'transition_curve_title': "2. Curva de Transición Dúctil-Fráxil",
        'transition_curve_desc': "Realice ensaios a distintas temperaturas para construír a curva.",
        'impact_log': "3. Rexistro de Impactos",
        'resilience_formula': "Resiliencia $\\rho = KCV / S_0$ (J/cm²)",
        'clear_data': "Borrar Datos",
        'material_col': "Material",
        'temp_col': "Temp (°C)",
        'energy_col': "Enerxía (J)",
        'fracture_type_col': "Rotura",
        'add_points_temp': "Engada puntos ensaiando a diferentes temperaturas.",
        'help_elastic_zone': "Zona Elástica: O material deforma pero volve á súa forma orixinal se se retira a carga. A pendente desta recta é o Módulo de Young (E).", // Aquesta clau ja existia
        'initial_height': "Altura Inicial:",
        'final_height': "Altura Final:",
        'help_yield_point': "Límite Elástico (Fluencia): Punto onde o material comeza a deformarse plásticamente (de forma permanente).",
        'help_plastic_zone': "Zona Plástica: O material sofre unha deformación permanente. Aínda que se retire a carga, non recuperará a súa forma inicial."
    }
};

/**
 * Estableix l'idioma seleccionat, el desa i aplica les traduccions.
 * @param {string} lang - El codi de l'idioma (p. ex., 'ca', 'es').
 */
function setLanguage(lang) {
    localStorage.setItem('language', lang);
    applyTranslations();
    // Oculta el menú desplegable després de la selecció
    const langMenu = document.getElementById('lang-menu');
    if (langMenu) {
        langMenu.classList.add('hidden');
    }
}

/**
 * Aplica les traduccions a tots els elements marcats amb 'data-translate'.
 */
function applyTranslations() {
    const lang = localStorage.getItem('language') || 'ca';
    const dictionary = translations[lang] || translations['ca'];

    document.querySelectorAll('[data-translate]').forEach(el => {
        const key = el.getAttribute('data-translate');
        if (dictionary[key]) {
            // Casos especials per a elements que no usen innerHTML
            if (el.tagName === 'OPTGROUP') {
                el.label = dictionary[key];
            } else if (el.tagName === 'OPTION') {
                // Per a les opcions dins d'un select
                el.textContent = dictionary[key];
            } else {
                // Cas general
                el.innerHTML = dictionary[key];
            }
        }
    });

    // Demana a MathJax que torni a processar la pàgina per renderitzar les noves fórmules
    if (window.MathJax && window.MathJax.typeset) {
        window.MathJax.typeset();
    }
}
